### ISSUE TITLE
chrome:// favicons not displayed

### ISSUE THREAD

**Issue by eoger** [eoger/tabcenter-redux#10]
Probably because we don't have the authorization to load them.  
Could we hijack that and show our own set of icons?

**Comment by Smile4ever** [comment]
Is this the same issue?

Security Error: Content at moz-extension://9596d62c-b25e-4401-8007-6345e51769ee/tabcenter.html may not load or link to chrome://mozapps/skin/extensions/extensionGeneric-16.png.

**Comment by eoger** [comment]
Something that Keith noted: we can load some chrome favicons (see about:preferences)

**Comment by ariasuni** [comment]
I opened [a bug report for Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1462948) for the long-term solution.
