### ISSUE TITLE
Right click menu doesn't have native style and entries

### ISSUE THREAD

**Issue by jplatte** [eoger/tabcenter-redux#115]
This is a problem for me in particular because I'm using [Context Plus](https://github.com/totallymike/contextPlus), which adds an entry to the right-click menu.

**Comment by jplatte** [comment]
Oops, just found #6. This is a duplicate.

**Comment by eoger** [comment]
Duplicate of #6.
However if we ever get native context menus I'm not sure how it would play together with other extensions.
