### ISSUE TITLE
Pin icon in dark theme is nearly invisible

### ISSUE THREAD

**Issue by Manishearth** [eoger/tabcenter-redux#122]
<img width="172" alt="image" src="https://user-images.githubusercontent.com/1617736/28844088-55ea72e4-76b8-11e7-9158-2ba8ab1c7161.png">

It's hard to see the pinned tab icon for any tab but the selected one. Perhaps it should be lighter?

**Comment by eoger** [comment]
Related https://github.com/eoger/tabcenter-redux/pull/111
