### ISSUE TITLE
"Status" favicon in Slack doesn't sync properly

### ISSUE THREAD

**Issue by nicholasbishop** [eoger/tabcenter-redux#125]
[Slack](https://slack.com) uses the favicon to show notify of new messages, e.g. a direct message gets a red dot. With tabcenter-redux the favicon does update, but it tracks behind the favicon in the regular tab bar. Reloading the page or switching between channels in Slack refreshes the favicon to the correct state.

Example screenshot:

![image](https://user-images.githubusercontent.com/1023208/28894364-a0305f04-77a2-11e7-8510-21957aeb673d.png)

**Comment by eoger** [comment]
Probably fixed by https://github.com/eoger/tabcenter-redux/commit/3032a8c74f1c199ce217e97b0f7d7cecf4224c82

**Comment by nicholasbishop** [comment]
Confirmed that in the latest release it appears to be working. Thanks :)
