### ISSUE TITLE
Display "Send Tab to Device" menu for tabs on sidebar

### ISSUE THREAD

**Issue by upsuper** [eoger/tabcenter-redux#130]
Currently, tabs in sidebar don't have "Send Tab to Device" in their context menu. It would be handy if it includes that.

**Comment by mlissner** [comment]
I actually appreciate that on Nightly this has moved to the URL bar. Seems like a more centralized spot for page-related actions. I like that only tab-related options are in the right click.

**Comment by eoger** [comment]
Being in the Sync team I'm able to answer that, at the moment we have no plans to offer that API, but this might change in the future if enough people want it (and I'll be the first one to implement it in an extension :)). Closing for now.
