### ISSUE TITLE
Show tabcenter with a hotkey

### ISSUE THREAD

**Issue by lopis** [eoger/tabcenter-redux#131]
I rarely open other sidebars like History, but when I do, it's with CTRL+H. There should be a shortcut for showing the tab center.

Seems like the suggested key is currencly CTRL+SHIFT+O which is already taken by Firefox (opens 'Other Bookmarks' window).

```
"_execute_sidebar_action": {
      "suggested_key": {
          "default": "Ctrl+Shift+O",
          "mac": "Command+Shift+O"
      }
}
```

**Comment by chchch** [comment]
Hi,

I was also about to raise this issue. Maybe Ctrl+Shift+\  would be a good substitute? It's not currently in use, and the combination can be comfortably pressed with the left hand alone.

**Comment by chris-kahn** [comment]
@chchch not on US keyboards it's not...

It would be nice if this shortcut could be configurable.

**Comment by Smile4ever** [comment]
> It would be nice if this shortcut could be configurable.

UI for re-assigning command shortcuts
https://bugzilla.mozilla.org/show_bug.cgi?id=1303384

**Comment by gutigen** [comment]
Is this shortcut a thing yet? I honestly can't tell :)

**Comment by EvanHahn** [comment]
I'm not sure if it's documented, but Ctrl+Shift+O (or ⌘+Shift+O on macOS) opens and closes the sidebar for me.

**Comment by lopis** [comment]
I saw on the source code that there is a shortcut but it's not working for
me in linux

**Comment by phisco** [comment]
On linux Ctrl+Shif+O opens the Library (aka History/Bookmarks/Downloads) in a different window and there is no way to remap firefox's hotkeys by default.

**Comment by eoger** [comment]
Quick update: work in [under way](https://bugzilla.mozilla.org/show_bug.cgi?id=1421811) to allow users to update commands hotkeys.

**Comment by cmonr** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1421811 was merged and release dtwo months ago.

It's working wonderfully! Bouncing from Windows to Linux is now a bit less painful.
