### ISSUE TITLE
Add description of "Compact Mode" option

### ISSUE THREAD

**Issue by Jiehong** [eoger/tabcenter-redux#132]
Hi,

First, thanks for this nice add-on!!

I'm starting using it with FF 55, and so far, it works quite alright! (on the right side).

However, the option "Compact Mode" has no description (like a tool-tip) of what it is supposed to do, and activating it doesn't seem to do anything for me.

Perhaps adding an information tool-tip could be useful?

**Comment by eoger** [comment]
When you have a lot of tabs, they go in compact mode automatically, which is probably what is happening here.
