### ISSUE TITLE
Grey out unloaded tabs

### ISSUE THREAD

**Issue by Jiehong** [eoger/tabcenter-redux#133]
Hi,

Today, with FF 55, unloaded tabs appear the same as loaded tabs in the sidebar.

Perhaps they should be greyed-out before they are loaded, just as in the regular tab-strip?

**Comment by eoger** [comment]
It doesn't seem that info is available yet: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/Tab

**Comment by Smile4ever** [comment]
What about "discarded", @eoger?

**Comment by eoger** [comment]
Nice, I didn't see they updated the tabInfo properties!

**Comment by Keith94** [comment]
Seems to be https://bugzilla.mozilla.org/show_bug.cgi?id=1377733 ?

**Comment by jmozmoz** [comment]
tab.discarded has been implemented in 57.0 by ttps://bugzilla.mozilla.org/show_bug.cgi?id=1377733 It would also be useful to add the unread attribute to tabs in the sidebar.
