### ISSUE TITLE
App possibility to open link to new tab, but at the end of the current list of tabs

### ISSUE THREAD

**Issue by Jiehong** [eoger/tabcenter-redux#134]
Hi,

Today, with FF 55, when opening a link in a new tab from a given tab, the new tab will open directly after the current tab.

However, I often expect that the new tab should appear at the bottom of the list of tabs instead, and not immediately after, as it breaks the logical order.

**Comment by Smile4ever** [comment]
"Related" tabs are the default, this bug asks an option to disable those (like browser.tabs.insertRelatedAfterCurrent, I think).

**Comment by fbruetting** [comment]
Please not by default! But optional would be of use, if this tab starts a new topic with it’s own „sub-tabs“ following. :)

**Comment by dos1** [comment]
I think that's outside of the Tab Center Redux's control and scope.

**Comment by eoger** [comment]
> I think that's outside of the Tab Center Redux's control and scope.
Indeed, my objective is to keep the add-on relatively options-free.
