### ISSUE TITLE
on the right side?

### ISSUE THREAD

**Issue by delphinuz** [eoger/tabcenter-redux#136]
Will it support on the right side function? Thanks.

**Comment by Screwtapello** [comment]
This is built into Firefox. Once the addon is installed and the tab-sidebar is visible, click the drop-down list of available sidebars and choose "Move Sidebar to Right".

**Comment by delphinuz** [comment]
Got it! Thansk!

Maybe it's a good idea adding those options in addons option menu.

**Comment by lopis** [comment]
This is unrelated to the addon. It's a firefox feature to be able to move the sidebar (the same sidebar that contains History, Bookmarks, etc) to the right side. Tabcenter just happens to reside in that sidebar.
