### ISSUE TITLE
Add-ons Manager lacks proper favicon

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#137]
Should be `chrome://mozapps/skin/extensions/extensionGeneric-16.svg`

![firefox_2017-08-09_07-18-09](https://user-images.githubusercontent.com/5490615/29126513-6b9380b0-7cd3-11e7-9061-a9b95307e830.png)

**Comment by yfdyh000** [comment]
#10.

**Comment by Keith94** [comment]
Weird that it can load about:preferences icon but not the about:addons one. Closing as duplicate anyway.

**Comment by eoger** [comment]
The pref icon is in `chrome://browser/skin/settings.svg`.
The addon one is in `chrome://mozapps/skin/extensions/extensionGeneric-16.svg`.
I wonder if we're allowed to load one bug not the other.
