### ISSUE TITLE
When entering responsive design mode, tab starts misbehaving

### ISSUE THREAD

**Issue by lopis** [eoger/tabcenter-redux#140]
I fnially understood how to reproduce this bug.

1. Open any website
2. Enter responside design mode (CTRL+SHIFT+M). If you look at Tabcenter, you will notice that a new tab appears for a few split seconds and then disappears.
3. The tab died. You can still select this tab, but it's not highlighted anymore in tabcenter. If you close the current tab, a ghost tab lingers. If you close and open the tabcenter sidebar, the ghost tab disappears.

Console error when entering RDM:

```
tab.url is undefined  tabManager.js:91

	<anonymous> moz-extension://09458ec2-4979-4d2f-9605-a7e9896f8e79/js/tabManager.js:91:1
	runSafeSyncWithoutClone resource://gre/modules/ExtensionUtils.jsm:61:14
	runSafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:176:38
	fire resource://gre/modules/ExtensionChild.jsm:763:71
	receiveMessage resource://gre/modules/ExtensionChild.jsm:765:76
	_callHandlers/< resource://gre/modules/MessageChannel.jsm:587:17
	_callHandlers resource://gre/modules/MessageChannel.jsm:586:14
	_handleMessage/deferred.promise< resource://gre/modules/MessageChannel.jsm:651:7
	_handleMessage resource://gre/modules/MessageChannel.jsm:648:24
	_handleMessage self-hosted:949:17
	receiveMessage resource://gre/modules/MessageChannel.jsm:163:5
```

**Comment by eoger** [comment]
Are you using another "tab management addon"? This addon ID "09458ec2-4979-4d2f-9605-a7e9896f8e79" doesn't look like tab center.

**Comment by lopis** [comment]
I came to the same conclusion when I failed to find this file manager.js inside the addon. I'll try to dig deeper but it seemed like this was a file from Firefox itself. I think I don't have any other tab managers installed but will have to get back on you on that.

**Comment by lopis** [comment]
Ok, follow up. Seems like this error is not connected to the cause, but it's just a consequence of the bug. It was thrown by.. the Duck Duck GO addon 😕 
The issue still occured when I disabled DDG.

**Comment by LakenH** [comment]
I having a similar issue with responsive design mode and Tab Center Redux. Once entering responsive design mode it gets very buggy, for example it loses its highlighting the tab is selected, it keeps the last opened tab highlighted, etc. Once responsive design mode is disabled it still misbehaves; until the tab center is refreshed

**Comment by lopis** [comment]
@LakenH same behaviour as me then. It happens even without any other addons enabled. It seems like an obscure Firefox hack that duplicates a tab when openning RDM, but TCR is not expecting it.

**Comment by LakenH** [comment]
Also related, Tab Center Redux seems to sometimes show 'fake tabs' after use of responsive design mode.
![image](https://user-images.githubusercontent.com/6951224/29217978-5348dc08-7e81-11e7-8432-24c88f1e8d20.png)
  
When clicked it's a plain white page, it shows in the top tab bar however it cannot be clicked there. I think @lopis is onto something with it being some Firefox hack with how RDM works.
  
I haven't been able to reliably reproduce this, but I do notice my tabs filling up with them from time to time.

**Comment by eoger** [comment]
Not much we can do here on the tab center side, make sure to [report that bug](https://bugzilla.mozilla.org/enter_bug.cgi?format=guided).

**Comment by mlissner** [comment]
FWIW, I just noticed today that you can't use responsive design mode on container tabs. Possibly related?

**Comment by eoger** [comment]
Probably fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1404088
