### ISSUE TITLE
favicon heavily aliased

### ISSUE THREAD

**Issue by quilloss** [eoger/tabcenter-redux#143]
The favicons displayed in the sidebar are heavily aliased. I think the extension might be downscaling the highest resolution image in the ico instead of using the 16x16 image.

Example:
https://en.wikipedia.org/favicon.ico

**Comment by eoger** [comment]
Not sure if we can really do something here, but that would be nice to have.

**Comment by quilloss** [comment]
Remove this rule ```image-rendering: -moz-crisp-edges;```?
Then 16px icons are noops while larger icons are less aliased but blurrier.
