### ISSUE TITLE
Open new tabs at the top of the list

### ISSUE THREAD

**Issue by kumar303** [eoger/tabcenter-redux#144]
Just like Tab Center, there should be a preference to make new tabs open at the top of the list, not the bottom. This is crucial for when you have a long list of tabs.

**Comment by Keith94** [comment]
Duplicate of #5.

**Comment by kumar303** [comment]
For now, I am able to use a separate add-on to achieve the same functionality: https://github.com/autonome/Always-Right

**Comment by eoger** [comment]
Thanks for spotting the duplicate. Closing.
