### ISSUE TITLE
Makes Firefox slower for some pages

### ISSUE THREAD

**Issue by kkot** [eoger/tabcenter-redux#145]
I noticed this addon slow down considerably Google Street View. When I was trying to look around it works very unsmoothly to the point it is unusable. Also switching between images is slower.

**Comment by gaby2300** [comment]
The same happened with Tab Center as a Test Pilot experiment.

​​

**Comment by eoger** [comment]
I wonder if it's because of the [thumbnails update code](https://github.com/eoger/tabcenter-redux/blob/master/src/tablist.js#L111). Do you experience the same slowness if the compact mode is enabled? (no thumbnails)

**Comment by kkot** [comment]
When I turn on compact mode it works better. Thanks :) I thought it would not make difference because I have so many tabs that I don't see thumbnails anyway but it does.

I see it for example here without compact mode switching between thumbnails is slow (with left and right buttons):
https://www.otodom.pl/oferta/dom-172-60-m-gdynia-ID3jqJG.html#gallery-open[3]

**Comment by eoger** [comment]
There's also the fact that we are not resizing the thumbnail firefox gives us, after a bunch of tabs loaded these binary blobs might add up, maybe we should resize them.

**Comment by eoger** [comment]
2 things we should do to get started:
- Use canvas to resize thumbnails.
- De-bounce the capture of thumbnails.

**Comment by eoger** [comment]
Let's see if https://github.com/eoger/tabcenter-redux/commit/a1f3ff2099195fd5efad0d6e4a282340ca04e2f7 helps

**Comment by eoger** [comment]
Feel free to re-open if Tab Center still causes performance issues.
