### ISSUE TITLE
add an option to hide or only display the icons of the pinned tabs

### ISSUE THREAD

**Issue by bitonic** [eoger/tabcenter-redux#149]
I have tons of pinned tabs (~15) and I liked Tree Style Tab's way of dealing with them -- displaying only the favicon instead of a whole "row".

Would it be possible to do the same with tabcenter-redux? Or alternatively hide them since i see the pinned tabs at the top anyway...

**Comment by eoger** [comment]
This might interest you https://github.com/eoger/tabcenter-redux/pull/106

**Comment by bitonic** [comment]
ah yes, that looks nice! i'll follow that.

**Comment by eoger** [comment]
I might also be do-able using only CSS, which https://github.com/eoger/tabcenter-redux/issues/151 covers

**Comment by bam80** [comment]
What about not only pinned tabs but all others tabs? I like the way all the tabs auto-hided in the Tab Center. For now, they takes too much space to be always visible..

**Comment by eoger** [comment]
#106 got merged, closing this.
