### ISSUE TITLE
Allow users to inject custom CSS

### ISSUE THREAD

**Issue by eoger** [eoger/tabcenter-redux#151]
A lot of users are in fact power-users of Firefox and would like to customize the Tab Center appearance to fit their needs.  
While we can't have an option for every part of the UI, a good cheap solution would be to allow users to inject their own CSS through the options page.

**Comment by Smile4ever** [comment]
Cool! Thanks a lot!

**Comment by bam80** [comment]
>`#topmenu{display:none;}`

Doesn’t work for me. Only side-bar's menu (with Gear icon) gets hided. Top tabs row still intact

**Comment by Smile4ever** [comment]
It's for hiding the new tab button, the search box and the gear icon. Are you talking about pinned tabs? Those are in a different container.
