### ISSUE TITLE
Vertical shift when resizing sidebar

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#157]
Seems to be caused by the `#newtab-label` appearing/disappearing.

![2017-08-22_01-18-36](https://user-images.githubusercontent.com/5490615/29555600-0ac0cec8-86d8-11e7-8868-efd8ffd3d220.gif)

**Comment by eoger** [comment]
Probably needs a height css rule somewhere.

**Comment by Keith94** [comment]
`#topmenu { min-height: 36px; }` fixes that for me.

**Comment by Keith94** [comment]
Fixed by latest commit.
