### ISSUE TITLE
Implement new tab loading/progress indicator animation

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#158]
https://bugzilla.mozilla.org/show_bug.cgi?id=1352119

This feature just landed in Nightly 57.0a1. Hoping that it could be implemented in Tab Center Redux.

**Comment by Jiehong** [comment]
I had a look at the change in the bug report, and this is less straight-forward as I thought:

The current spinner is a simple svg with an animation embedded in it, while the new one has some css animation going-on.

As the spinner is currently added to an icon in place of the favicon, as an image, it makes it less easy to adapt.

Quick bug commit reference on FF: https://hg.mozilla.org/integration/mozilla-inbound/rev/de253c538644

**Comment by asamuzaK** [comment]
Feel free to use it if you like.
[sidebarTabs/loading.svg](https://github.com/asamuzaK/sidebarTabs/blob/master/src/img/loading.svg?short_path=62195a0 "sidebarTabs/loading.svg at master · asamuzaK/sidebarTabs")

I think you should change `fill: context-stroke` to something like `fill: HighLight`.
