### ISSUE TITLE
Make the top menu stand out better

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#159]
The top menu element looks very similar to the (compact) tabs in height/color, so it blends in quite easily.
I don't know if something should be done to improve it/make it stand out more, but some suggestions:

* Add a light box-shadow below it similar to the popups in Firefox:

![image](https://user-images.githubusercontent.com/5490615/29587100-b29c8876-8741-11e7-8ce4-ee9fe5ceb450.png)
* Make the background color white (#fff) to match the sidebar header.
etc...

**Comment by eoger** [comment]
<img width="247" alt="screen shot 2017-08-23 at 8 44 18 pm" src="https://user-images.githubusercontent.com/6424575/29644415-d96f8f4a-8843-11e7-81d2-4573dfcbdd84.png">

In my case the header is actually transparent, but yeah it would be nice to have

**Comment by Keith94** [comment]
Covered by #308.
