### ISSUE TITLE
Tree style?

### ISSUE THREAD

**Issue by rubdos** [eoger/tabcenter-redux#160]
I used the "Find a Replacement" button in `about:addons` on Tree Style Tabs, and AMO points here.

Is there any intent on having such (tree style) functionality? It's not that I can't live without it, but grouping tabs was something I appreciated a lot. In any case, vertical tabs already help a *lot*, thanks for the effort!

**Comment by eoger** [comment]
I _**may**_ accept a PR if the implementation is clear and fairly self contained.

**Comment by rubdos** [comment]
> I may accept a PR if the implementation is clear and fairly self contained.

Good, that's what I wanted to hear. I currently have no time, but someone Googling this might have. Or me, in a future universe.

**Comment by eoger** [comment]
[Tree Style Tab](https://addons.mozilla.org/firefox/addon/tree-style-tab/) is now a webextension, closing!
