### ISSUE TITLE
Feature request: clicking on the highlighted tab does an 'ctrl tab'

### ISSUE THREAD

**Issue by quesada** [eoger/tabcenter-redux#162]
This is a Feature that I love from another legacy addon: clicking on the highlighted tab does an 'ctrl tab'. You don't know how convenient this is till you try it.

**Comment by mlissner** [comment]
What does ctrl tab do? Doesn't seem to have any effect for me?

**Comment by eoger** [comment]
Closing because I have no idea what this is about.
