### ISSUE TITLE
Open the tabs sidebar automatically

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#164]
Apparently sidebars can be opened automatically now that https://bugzilla.mozilla.org/show_bug.cgi?id=1341126 landed.

**Comment by bwinton** [comment]
When would you want it to open automatically?  (The WebExtension code should already open it automatically when you install the add-on…)

**Comment by Keith94** [comment]
I thought about opening the sidebar in a new session or window, if it was previously closed in the last session/window. Thoughts?

**Comment by Keith94** [comment]
One user mentions it in their review as well:

>The only thing that bothers me is the tab "sidebar" is closed when starting Firefox--you have to manually open it every time.

https://addons.mozilla.org/en-US/firefox/addon/tab-center-redux/reviews/904578/

**Comment by Screwtapello** [comment]
I have a session with multiple windows. One of them is for general browsing, so I keep it big, and it has a lot of tabs open so I use Tab Center Redux to manage them. Other windows are for viewing documentation, etc. for specific projects. They're small windows, so I can't spare the screen real-estate for Tab Center and they only have two or three tabs at most, so it's no a big deal.

I use Nightly, so I restart my browser once a day. For a while, after restarting all the windows would have Tab Center open, so I'd close it in the small ones. The next day after restarting, no windows would have a sidebar open, so I'd open it in the main window. The next day after restarting, all te windows would have Tab Center open...

Recently, I've noticed that after restarting, no windows ever have Tab Center open, no matter how many times I've opened it before. That's beginning to get a bit annoying.

**Comment by eoger** [comment]
Maybe P1 is a bit too much, just making sure it doesn't fall under my radar. This behavior is super annoying.

**Comment by Screwtapello** [comment]
Actually, my issue is probably https://bugzilla.mozilla.org/show_bug.cgi?id=1385630

**Comment by eoger** [comment]
Quick check: can't use that API in a background script, it can only be triggered following a user action :/

**Comment by grahamperrin** [comment]
> … The WebExtension code should already open it automatically when you install the add-on…

In addition, I expect the sidebar to open in response to enabling the extension. 

(Is that beyond the scope of this extension? Is there, should there be, a WebExtensions API for such things?)

Non-appearance caused me to report #166 … my bad for not properly investigating before reporting the issue `:-/` but it _is_ reasonable to expect a feature to appear after enabling the feature.

**Comment by eoger** [comment]
Can't do much here which is kinda sad, closing :(
