### ISSUE TITLE
Add option to hide sidebar when there is only one tab in the current window

### ISSUE THREAD

**Issue by Smile4ever** [eoger/tabcenter-redux#168]
It would be nice to have an option to hide sidebar when there is only one tab in the current window.

Firefox itself has a similar feature / option for the tab bar. I would use this when I have multiple windows open next to each other to maximize the useful screen estate.

**Comment by Keith94** [comment]
I don't think Firefox has a feature like that, correct me if I'm wrong. Anyways, if you're only working with 1-2 tabs, it could be kinda jarring having the sidebar open and close frequently. Better to just have a dedicated button to toggle it, in my opinion.

**Comment by eoger** [comment]
Yup and we can't re-open the sidebar ourselves anyway.

**Comment by Smile4ever** [comment]
@Keith94 Firefox had a feature like that, see this comment:
https://bugzilla.mozilla.org/show_bug.cgi?id=1332447#c125

**Comment by Keith94** [comment]
I added a workaround here: https://github.com/eoger/tabcenter-redux/wiki/Custom-CSS-Tweaks#hide-sidebar-with-only-one-tab-open
