### ISSUE TITLE
Add toolbar button to toggle sidebar

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#171]
I suggest adding a dedicated toolbar button that toggles the Tab Center sidebar. It can be useful for new users to discover how the add-on is actually used (for example #166), and just in general as well.

**Comment by iansan5653** [comment]
There is a dedicated toolbar button. It looks like this: 
![image](https://user-images.githubusercontent.com/2294248/30784511-5b5cb4bc-a124-11e7-826e-441d38e1f7b3.png)

**Comment by Smile4ever** [comment]
There exists a button already, but it might be worth adding a browserAction for Tab Center Redux:
* It toggles the sidebar, not Tab Center Redux specifically
* You could add context menu items to the browserAction (to navigate to the preferences, ...)

**Comment by Keith94** [comment]
Yeah, should have a separate button to toggle TC specifically, not just the last sidebar you had open.

**Comment by chriskuipers** [comment]
Yeah good idea! Or put this explaination on the front/wiki page, I had to dive in to this Issues section to figure out how to re-toggle the bar :)

**Comment by asciijungle** [comment]
I like the idea. I'd also love to have a **keyboard shortcut** coming with it!

**Comment by kkot** [comment]
I think it is good idea. Tree Style Tab has it and it is useful because it save one click after for example using History and also good for discover-ability.

![obraz](https://user-images.githubusercontent.com/1009806/32627484-dd655288-c592-11e7-99bd-b757554e0ee3.png)
