### ISSUE TITLE
Tabs moved from one window to another are frozen in Tab Center Redux (but not in Firefox)

### ISSUE THREAD

**Issue by benmullins** [eoger/tabcenter-redux#174]
To reproduce:
---------------

Drag a tab from one window to another window.

What should happen:
----------------------

Tab is in place in the new window and can be interacted with normally.

What does happen:
--------------------

Tab appears at the bottom of the tab list in the new window. When it is focused, the previously focused tab remains highlighted in Tab Center Redux. When it is moved, the change is reflected in the native tab strip, but the tab remains at the bottom of the list in Tab Center Redux. When Tab Center Redux is disabled and re-enabled (or Firefox is restarted) the true order of tabs is displayed again and the tab can be focused and moved normally again.

I don't know for sure one way or the other, but I suspect that the tab being placed at the end of the list can't be practically addressed within the constraints of the WebExtensions API. The other problem, however, seems like it's purely a bug.

**Comment by eoger** [comment]
Thanks a lot for the report it was a pretty bad one!
