### ISSUE TITLE
Add option to hide horizontal tabs

### ISSUE THREAD

**Issue by Vityacv** [eoger/tabcenter-redux#175]
Horizontal tabs are useless (at least for me) if you have added "Tabs" sidebar.

**Comment by Vityacv** [comment]
Maybe it will be possible with this api? https://bugzilla.mozilla.org/show_bug.cgi?id=1384515

**Comment by Smile4ever** [comment]
You are looking for https://bugzilla.mozilla.org/show_bug.cgi?id=1332447

**Comment by benmullins** [comment]
Yes, this is currently impossible to achieve _automatically_ with the WebExtensions API, but until this changes it's possible to remove the native tab bar by adding this to userChrome.css:

```
#TabsToolbar { visibility: collapse; }
```

**Comment by bam80** [comment]
@benmullins 
>`#TabsToolbar { visibility: collapse; }`

Should it work if filling in "Custom stylesheet" Advanced Setting? https://github.com/eoger/tabcenter-redux/issues/151
Seems do not works for me in Firefox 56.0

**Comment by Smile4ever** [comment]
You need to put

    #TabsToolbar { visibility: collapse; }

in userChrome.css. This is something Firefox-specific that Tab Center Redux cannot do due to the current technical limitations. The CSS option in Tab Center Redux allows you to change Tab Center Redux, not Firefox itself.

**Comment by eoger** [comment]
Duplicate of #15
