### ISSUE TITLE
[Featrue request] Auto focus on tab search bar after sidebar opened

### ISSUE THREAD

**Issue by 70599** [eoger/tabcenter-redux#178]
Auto focus on tab search bar after sidebar opened.
Is this possible?
![screenshot](https://user-images.githubusercontent.com/5929170/31128369-28185f7c-a884-11e7-9882-0c1d4d46c406.png)

**Comment by eoger** [comment]
I don't believe this is possible for a WebExtension sidebar to request the focus at the moment :(

**Comment by eoger** [comment]
Closing as this is superseded by #173
