### ISSUE TITLE
'WEB_EXT_FIREFOX' is not recognized error

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#180]
I'm getting an error in the command prompt when trying to run `WEB_EXT_FIREFOX=nightly npm run dev` as per the readme. It says:

>'WEB_EXT_FIREFOX' is not recognized as an internal or external command,
operable program or batch file.

I used `npm i` previously and `npm run dev` works fine for me. I'm curious as to why WEB_EXT_FIREFOX doesn't work for me since I do have Nightly installed.

**Comment by eoger** [comment]
It looks like you're trying to launch this from a windows default cmd shell:
I think you have to [set the env variable in a different way](https://superuser.com/questions/1049430/how-do-you-set-environment-variables-for-a-single-command-on-windows) that on unix systems.

**Comment by Keith94** [comment]
Thanks for the link, now I got it to work on Windows by entering:

```
set WEB_EXT_FIREFOX=nightly
```

Followed by:

```
npm run dev
```

Not sure if it's worth adding to the readme, you decide. ;)
