### ISSUE TITLE
Throbber animations should be synchronized

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#181]
When multiple tabs are loading simultaneously, the new Photon throbbers (d8c1696) should be synchronized with each other. Currently they are not synchronized.

See also: https://dxr.mozilla.org/mozilla-central/source/browser/base/content/tabbrowser.xml#620

**Comment by eoger** [comment]
Should be pretty easy, if someone really cares about it :)

**Comment by Keith94** [comment]
I think it's important, and good to have parity with the native tabs as much as possible.
