### ISSUE TITLE
Allow styling of unread and busy tabs

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#183]
For tabs which are unread or still connecting ("busy" state), there should be a way for users to change the styling of them, for example by using `.tab.unread` or `.tab.busy` in the add-on's CSS stylesheet.

**Comment by eoger** [comment]
You mean like `.tab.loading` and `.tab.discarded`? :)
I have activated the wiki feature on this Github, I wonder if we could centralize all the CSS customizations to date there...

**Comment by Keith94** [comment]
>You mean like .tab.loading and .tab.discarded? :)

Oops, yes these work in the dev version, just not the release version yet.
Can you please add the `unread` class as well?

>I wonder if we could centralize all the CSS customizations to date there...

Good idea. Do you have to create a "homepage" for the wiki first?

**Comment by eoger** [comment]
> Can you please add the unread class as well?
Did this get implemented? I don't see it on MDN at the moment. I'm pretty interested actually (send tab uses this),

> Good idea. Do you have to create a "homepage" for the wiki first?
Do I? I'll add one just in case

**Comment by Keith94** [comment]
Hmm, maybe there is no proper implementation yet. But I think Tree Style Tab has [some way of doing it](https://github.com/piroor/treestyletab/blob/master/webextensions/common/tree/base.js#L184).

Also seems like I can't edit the wiki page myself for some reason.

**Comment by eoger** [comment]
Try now :)

**Comment by Keith94** [comment]
Works! I guess we can add userChrome.css and add-on-specific styles there if we wanted to?
