### ISSUE TITLE
Noscript Issue

### ISSUE THREAD

**Issue by devanes** [eoger/tabcenter-redux#185]
I have two machines with FF56 64 bit. On both of them I have Tab Center Redux (0.4.2) and NoScript (5.1.1). On one them Tab Center Redux works fine, on the other, the tab sidebar is empty and the new tab and preferences buttons on top of the sidebar do nothing. On the second machine, I have disabled all other addons. But this doesn't make any difference. Once I deactivate NoScript and restart, the tab sidebar works as expected.

**Comment by eoger** [comment]
Probably one of your NoScript rules on the 2nd machine, you could try exporting the rules from 1st machine and import them on the 2nd.

**Comment by devanes** [comment]
The settings are the same, I checked that. The only thing which differs is the whitelist.

**Comment by devanes** [comment]
I took a while to get to it, but it seems you suggestion did indeed fix the issue. Don't know why though. Why should noscript rules block the functionality of this addon? Does this addon get data from an external website?

**Comment by eoger** [comment]
Glad to hear that you have resolved your problem. The doesn't retrieve any remote data.
Will close, feel free to re-open if needed.
