### ISSUE TITLE
Tab list after Firefox restart (restore windows and tabs of last session) is shown in compact mode and cannot be changed to non-compact mode

### ISSUE THREAD

**Issue by jmozmoz** [eoger/tabcenter-redux#192]
If use the setting to restore the last session on start of Firefox. So the old windows/tabs are opened again. But the tab list created by tab center redux lists the tabs in compact mode and ignores the setting in the options page. If opening a new window the tabs there are shown according to the compact option. 

(I have tested this with Firefox 57.0b5 on two (Windows) computers. On one the numbers of tabs opened at (re)start was about 20 on the other about 200.)

**Comment by eoger** [comment]
Is there enough space for the tabs to actually be shown in non-compact mode? We shrink them when there's no space to show all of them without scrolling.

**Comment by jmozmoz** [comment]
Thank you for your answer. No, there would not be enough space for all the tabs. Is this behaviour documented somewhere? Can it be overwritten with user CSS?

**Comment by eoger** [comment]
You could overwrite these changes using CSS. The compact mode is toggled by setting the `.shrinked` class on the `#tablist` div.

**Comment by jmozmoz** [comment]
Unfortunatelly, it seems not possible to remove the .shrinked class with user CSS (or any other class: https://stackoverflow.com/a/4215432)

**Comment by eoger** [comment]
You can't, however you can reset its effects ;)
I would also accept a PR for the "Compact Mode" that allow 3 settings: Auto - Always Enabled - Always Disabled

**Comment by eoger** [comment]
Fixed by https://github.com/eoger/tabcenter-redux/commit/64ef3db748cc7f63cc649e4d2f465fc6c7544f08
