### ISSUE TITLE
Pinned favicons slightly too large

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#193]
In the new pinned tabs list, the favicons seem to be sized at 18px when it should be 16px. Notice how they're slightly blurrier:

![image](https://user-images.githubusercontent.com/5490615/31264264-b2fa9ee0-aa1c-11e7-8266-73f32cf82a4e.png)

**Comment by eoger** [comment]
Yeah I wanted slightly bigger favicons... but it looks like this is backfiring

**Comment by lopis** [comment]
I actually use CSS to make my favicons even bigger. 32px to be precise. But for some websites, the favicon still shows as 16px. Seems to be a limitation of firefox and there are a few bugs about it

https://bugzilla.mozilla.org/show_bug.cgi?id=860334
https://bugzilla.mozilla.org/show_bug.cgi?id=492172

@eoger Do you think there's any way to get the higher resolution icons for a website? Firefox (Nightly v58) seems to store those icons for other purposes, e.g. for `about:home`. In the following screenshot, the youtube favicon in the tab is 16x16 is is very blurry, but the shortcut in `about:home` is high resolution.

![image](https://user-images.githubusercontent.com/2715751/31381467-e70dcd24-adb4-11e7-99a8-8bc30edfd2ef.png)
