### ISSUE TITLE
Tab cannot be moved to the last position in the sidebar

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#197]
Here's a gif of trying to move a tab below the other tabs, and failing to do so. Also when you drag the bottommost tab downwards, it gets moved up one spot in the list.

![2017-10-10_20-48-24](https://user-images.githubusercontent.com/5490615/31421481-73ca2108-adfc-11e7-8f90-36c0f5126fb4.gif)

**Comment by Keith94** [comment]
I guess it only works if you drop the tab directly onto the bottommost tab. But one would assume it'd still work if you drop it onto the blank space below it.

**Comment by eoger** [comment]
I definitely reproduced that problem before, but I can't seem to do it now. Keeping that issue open until we figure it out.

**Comment by Keith94** [comment]
Strange, I can't reproduce it anymore either.

**Comment by Keith94** [comment]
Okay, I think I have found the steps to reproduce this annoying bug!

1. Open four tabs of any website, for example https://www.wikipedia.org/
1. Select one of the tabs
1. Right-click the selected tab and use "Move to New Window"
1. Go back to the first window
1. Try to drag the first tab to the last position via dragging and dropping into the blank space below the last tab, and you should see this bug

Let me know if that helps.

**Comment by eoger** [comment]
Thanks for the report
