### ISSUE TITLE
Make sidebar go the top / increase available vertical space

### ISSUE THREAD

**Issue by jhasse** [eoger/tabcenter-redux#198]
Just as it was in TabCenter.

If Firefox wouldn't want this kind of change done by extension, is there at least a way to hide the sidebar header (where you can switch to Bookmarks, History, ...)?

**Comment by Keith94** [comment]
>is there at least a way to hide the sidebar header (where you can switch to Bookmarks, History, ...)?

Yes, it can be hidden via userChrome.css. I added this to the wiki page: https://github.com/eoger/tabcenter-redux/wiki/Custom-CSS-tweaks

**Comment by eoger** [comment]
Closing since I can't do much here and there is a CSS tweak available.
