### ISSUE TITLE
Dropping tab onto bookmarks toolbar detaches the tab

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#201]
Commit 19217f9 should be improved to not cause this bug.

## Steps to reproduce
Drag and drop tab from sidebar onto bookmarks toolbar

## Expected results
Tab should be added to bookmarks

## Actual results
Tab is moved to new window

**Comment by eoger** [comment]
Also fixed by https://github.com/eoger/tabcenter-redux/commit/408ecb998fd4416cc59d34f42fe0937e79d7e66f
Wow, this patch really broke everything... Thank you for the reports @Keith94!

**Comment by Keith94** [comment]
My pleasure :)
