### ISSUE TITLE
Tab Sort Order

### ISSUE THREAD

**Issue by laktak** [eoger/tabcenter-redux#202]
I found the reversed tab order from TabCenter to be perfect.

Now that FF56 disabled TabCenter I came here looking for a replacement. Unfortunately I saw that you already closed #5 before I was aware of your extension.

Will you consider a PR for this feature?

**Comment by laktak** [comment]
OK, I found that you have a custom stylesheet option 👍 

So far this appears to work really well and restores the "old" functionality:

```
#tablist {
    flex-direction: column-reverse;
    display: flex;
}
```

**Comment by eoger** [comment]
Nice! Feel free to add it [on the wiki](https://github.com/eoger/tabcenter-redux/wiki/Custom-CSS-tweaks)

**Comment by Keith94** [comment]
This trick works well for a small amount of tabs, but opening lots of tabs kinda breaks the sidebar (tabs height decreases and scrolling is impossible).

**Comment by laktak** [comment]
@Keith94 try:

```
#tablist {
    flex-direction: column-reverse;
    display: flex;
    flex: 1 0 auto;
}
```

**Comment by Keith94** [comment]
Yep, that fixed it.

**Comment by Keith94** [comment]
@laktak Would you happen to know if there's a way to hide the scroll bar?

**Comment by laktak** [comment]
I took a quick look but it appears that Mozilla obsoleted the css for that.

**Comment by laktak** [comment]
@eoger if you want this as as PR we still have to add support for pinned tabs (the are currently shown at the bottom).

Btw, could you include a direct link to the css wiki below the css options box (for easier copy & pasting)?

**Comment by cmmartti** [comment]
This will keep the pinned tabs at the top:

```
#tablist {
  flex-direction: column-reverse;
  display: flex;
  flex: 0 0 auto;
}
.tab.pinned {
  order: 1;
}
```

I also updated the wiki.

**Comment by sancho-82** [comment]
This has the side effect of Pinned Tabs scrolling with the rest.

**Comment by eoger** [comment]
Closing this, feel free to update the CSS tweak wiki page if you find enhancements.
