### ISSUE TITLE
Drop inside the content area/outside the window should open a new window

### ISSUE THREAD

**Issue by eoger** [eoger/tabcenter-redux#204]
Filling this so it doesn't fall from my radar, the previous implementation didn't really work correctly and [was backed out](https://github.com/eoger/tabcenter-redux/commit/408ecb998fd4416cc59d34f42fe0937e79d7e66f).

**Comment by Keith94** [comment]
Duplicate of #102 ?

**Comment by eoger** [comment]
Ha yes good one.
