### ISSUE TITLE
Undo Close Tab affects other windows

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#208]
## Steps to reproduce
1. Open a few URLs in new tabs
2. Close the new tabs
3. Open a new Firefox window
4. Right-click on the tab in the new window and click "Undo Close Tab"

## Expected results
Undo close tab should be disabled or do nothing

## Actual results
The closed tab in the previous window is reopened

**Comment by eoger** [comment]
Nice one, indeed the implementation was incomplete.
