### ISSUE TITLE
Tab center does not always scroll to ensure the active tab is visible

### ISSUE THREAD

**Issue by StephGbzh** [eoger/tabcenter-redux#209]
First, thanks for your add-on, I used to use my own simple home-made vertical tabs extension based on XUL but with WebExtensions coming, I was pleased to find yours as a replacement !

I like my new tabs (CTRL+T) to always open after the current active tab. Firefox opens them by default at the end of the tab list. So I use the extension [Open Tabs Next to Current](https://addons.mozilla.org/en-US/firefox/addon/open-tabs-next-to-current/) so that CTRL+T, the New Tab button from TabCenter itself or from Menu > File all open the new tab where I want it.

I also often have more tabs than my screen height can show so the scroll bar appears.

Now let's say I have many tabs open and the current active tab is one of the first ones. When I hit CTRL+T:

1. a new tab is created at the end of the tabs list and becomes the active one
2. firefox and tab center both auto scroll to the end/bottom of the list to show this new tab
3. the extension "Open Tabs Next to Current" kicks in and moves that new tab back to just after the previously active tab (which is still the one near the beginning/top)
4. Firefox scrolls back towards the top, just enough to show our active new tab
5. Tab Center does NOT do that and stays focused on the bottom of the scroll bar where the active tab and the previously active tab are not visible at all... :(

Is it possible to ensure that Tab Center does the same thing as the native Firefox tab bar in this case?

**Comment by eoger** [comment]
I guess we would need to scrollIntoView() on tabs.onMoved(). I tried to do that but it didn't really work (because we are already scrollingIntoView)

**Comment by asciijungle** [comment]
Hi, I'm having the same issue as @StephGbzh. What tabcenter currently does is it scrolls to the bottom whenever I create a new tab. This happens even though the new tab is not being created at the bottom of the list.

**Comment by eoger** [comment]
I would accept a PR for that, but it is currently not a priority for me.

**Comment by peterallcdn** [comment]
Hello,

Just wanted to add that I too am experiencing this issue. Like the others, I'm using Open Tabs Next to Current to regain the functionality lost by Tab Mix Plus I believe. New tabs are brought into focus properly in Tree Style Tab extension but I prefer Tab Center.

Thanks for the great extension!

**Comment by benmullins** [comment]
It seems that in a future version of Firefox there will be a native setting for new tab location, which will obsolete extensions like Open Tabs Next to Current and presumably Just Work™ with Tab Center Redux since the source of the problem is the WebExtensions work-around that these extensions use (moving the new tab to the desired location after it is created at the end of the list).

See the relevant bugzilla entry here: https://bugzilla.mozilla.org/show_bug.cgi?id=1344749
