### ISSUE TITLE
Compact pinned tabs style issue

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#213]
When using compact pinned tabs, the sound icon, favicon, and tab height changes slightly when pinning/unpinning a tab. Adjustment should be made to prevent that "shifting" effect and keep it consistent.

![2017-10-22_13-46-36](https://user-images.githubusercontent.com/5490615/31866145-a6e3faa0-b72f-11e7-8650-49362e7331e4.gif)

**Comment by eoger** [comment]
It's very much an edge case, however if someone makes a PR I'll accept it.

**Comment by dos1** [comment]
There you are! Well, maybe I went too fast with "Closes #213" as I've left the overall size as is (because I think it's okay), but the sound icon displacement looked bad indeed so I've fixed it :)

**Comment by Keith94** [comment]
@dos1 Looks good to me. 👍
