### ISSUE TITLE
Add change log/release notes to updates

### ISSUE THREAD

**Issue by forteller** [eoger/tabcenter-redux#217]
The recent update did not have any changelog attached. That makes me go look for it other places, like here, where I still couldn't find it. I'd appreciate it a lot if you'd add it to the next release. Thank you! :) 
![screenshot from 2017-10-23 03-06-54](https://user-images.githubusercontent.com/343561/31868455-9e78807a-b78e-11e7-99e6-42a541f5a321.png)

**Comment by eoger** [comment]
Sorry about that, I got a bit sidetracked.

**Comment by eoger** [comment]
<img width="536" alt="screen shot 2017-10-23 at 2 38 33 am" src="https://user-images.githubusercontent.com/6424575/31875272-62e92e8a-b79b-11e7-9a59-494e0af07b47.png">

Done! Thank you for reminding me :)

**Comment by forteller** [comment]
Again there's a new update, this time with a bit scary note from Firefox telling me you want some new access I don't understand, without any release notes. This might make people a bit vary. Thank you for your work! Just please add this to your checklist :)

**Comment by eoger** [comment]
No worries! The changelog is actually [here](https://addons.mozilla.org/en-US/firefox/addon/tab-center-redux/versions/?page=1#version-0.6.1), but I had to release two hotfixes in the meantime :) (0.6.2 and 0.6.3)

**Comment by nirfse** [comment]
I apologize for bumping a closed issue, but I'd also ask to implement a proper Releases/Changelog maintenance into default routine of this project.
