### ISSUE TITLE
Tab context menu cut off

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#22]
If you right-click on a tab too close to the right edge, the menu appears cut off and the text wraps onto the next line. Is there a way to prevent that?

**Comment by eoger** [comment]
I haven't found a way, I'm open to suggestions

**Comment by eoger** [comment]
Ideally I'd rather not implement that menu myself, see https://bugzilla.mozilla.org/show_bug.cgi?id=1367160
