### ISSUE TITLE
Compact mode disabled + Compact pinned tabs disabled + lots of tabs = ....

### ISSUE THREAD

**Issue by eoger** [eoger/tabcenter-redux#221]
Scrollbars

<img width="261" alt="screen shot 2017-10-23 at 2 56 32 am" src="https://user-images.githubusercontent.com/6424575/31875835-e6d81f42-b79d-11e7-873f-ba3cecddc4cb.png">

**Comment by eoger** [comment]
This is caused by the overflow-x I added to avoid horizontal scrollbars. @dos1 if you have an idea..

![css](https://media.giphy.com/media/13XW2MJE0XCoM0/giphy.gif)

**Comment by dos1** [comment]
I think I've seen something like that when working on my old PR and somehow dealt with it. I'll play with it later today.
