### ISSUE TITLE
Fullsize pinned tabs?

### ISSUE THREAD

**Issue by Fitzsimmons** [eoger/tabcenter-redux#228]
I think the latest update miniaturized my pinned tabs but part of my reason for liking Tab Center so much was that it displayed my pinned tabs as fullsize. I like being able to see the titles, especially since the apps that run in those pinned tabs will update the title. Is there any way to get my pinned tabs back to appearing like normal tabs?

**Comment by eoger** [comment]
Yup, in the extension Settings untick "Compact Pinned Tabs"

**Comment by Fitzsimmons** [comment]
Thanks so much, can't believe I missed that! :man_facepalming:
