### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by jamienicol** [eoger/tabcenter-redux#23]
I use the "Compact Dark" (formerly dev edition) firefox theme. The original tab center matched those colours, but tabcenter-redux is light.

No idea whether this is possible with new API restrictions, or how upcoming photon changes affect this, but it would be nice.

**Comment by eoger** [comment]
I have no idea if this is possible or not, if someone could have a look for that I'd appreciate it.

**Comment by Keith94** [comment]
Maybe an option can be added to apply a dark theme via CSS, rather than determined by Firefox theme(?).
