### ISSUE TITLE
Wrong tab gets focus when closing new tab

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#231]
## Steps to reproduce
1. Have two tabs open
1. Select the first tab
1. Click on Tab Center's New Tab button
   * Tab should open at the bottom below the other two tabs
1. Make sure the new tab is selected
1. Close the new tab

## Expected results
First tab is focused because it's the [owner tab](http://kb.mozillazine.org/Browser.tabs.selectOwnerOnClose)

## Actual results
Second tab is focused instead of the first tab

**Comment by eoger** [comment]
Can reproduce.  
I believe this is a WebExtension bug though, so you might want to open a bug on Bugzilla instead.

**Comment by Keith94** [comment]
Okay, I'll consider it. Thanks for testing.
