### ISSUE TITLE
Add an indicator for a compact pinned tab's container

### ISSUE THREAD

**Issue by CharoSW** [eoger/tabcenter-redux#232]
When the pinned tabs are in compact mode there isn't any indication of which container it's in, whereas when the tabs are expanded they have the same container indicator as the rest of your tabs.  Considering the design an underline would probably suffice

**Comment by Keith94** [comment]
I agree, maybe the `.tab-context` should be displayed along the bottom of pinned tabs as such:

![image](https://user-images.githubusercontent.com/5490615/32142456-b0de59b8-bc54-11e7-9578-c067919a193d.png)

**Comment by sabi0** [comment]
It is not about the active tab "blue stripe", is it? It is not shown for compact pinned tabs either.
Should I create a separate issue for that?
