### ISSUE TITLE
"Loading" animations not synchronized

### ISSUE THREAD

**Issue by RalfJung** [eoger/tabcenter-redux#235]
## Short description

When there are multiple tabs loading, in the normal Firefox tabbar, the animation shown as tab icon is synchronized -- i.e., all these blue dots, as they move around, hot the left/right end of their movement at the same time.

## Steps to reproduce

Open multiple tabs that load long enough such that you can see multiple "loading" animations.

## Expected result

The animations should all be synchronized.

## Actual result

They are not synchronized.

## Environment

 * Platform (OS): Linux (Debian testing amd64)
 * Version of Firefox: 57.0b12
 * Version if Tab Center Redux: 0.5.1

**Comment by eoger** [comment]
Have you tried on Firefox Nightly? https://github.com/eoger/tabcenter-redux/commit/488185eadd608da7f6ea3c079498c9882a78e723 mentions that the API required to achieve this result is only available there.

**Comment by RalfJung** [comment]
Ah, I did not know that, sorry. I guess this can be closed then?

**Comment by dos1** [comment]
I wonder if it's actually intended to not have such APIs available in the WebExtension context...

**Comment by eoger** [comment]
It does work for me though.

**Comment by dos1** [comment]
On which version? Works for me on Nightly as well (should work on Developer Edition too), just not on beta :)
https://developer.mozilla.org/en-US/docs/Web/API/Document/getAnimations

**Comment by eoger** [comment]
Closing since 57 will be out in a few hours, please re-open if you see this behavior again.

**Comment by RalfJung** [comment]
Not sure what you mean, I have seen this on the 57 beta all along? Or do you mean that 58 beta will have the necessary API to fix this?

**Comment by dos1** [comment]
Yeah, it's not exactly related to 57, as it's not tied to the version number; right now it's enabled only on Nightly channel, regardless of the release.

**Comment by eoger** [comment]
Which version of Tab Center redux are you using?

**Comment by RalfJung** [comment]
> Which version of Tab Center redux are you using?

I'm on 0.5.4.

**Comment by eoger** [comment]
When you open the console (Ctrl+Alt+K), what does entering `document.body.getAnimations` returns?

**Comment by RalfJung** [comment]
Ctrl-Alt-K doesn't do anything. You don't mean the "Browser Console", do you? That one says that there is no `document.body`.

**Comment by eoger** [comment]
Sorry I meant the content console, I think you can still check this in the browser console with `document.getAnimations`

**Comment by dos1** [comment]
Just checked it again and reality confirms what's written in MDN - the browser UI context has access to Animations API since Firefox 48, but in the content context (where Tab Center Redux runs) it's enabled only in Nightly and Developer Edition, also since Firefox 48.

Until Mozilla flips the "ship it in beta and release channels" switch (or at least "enable it in WebExt context too" one), it will be available only in Nightly, regardless of the version number.

**Comment by eoger** [comment]
Nice investigation!

**Comment by eoger** [comment]
The pref to flip is `dom.animations-api.core.enabled`, I can confirm it works, just tested it with Firefox 57 release.

**Comment by RalfJung** [comment]
I don't know what the content console is, is that the "console" shown when I hit F12? That one doesn't even have a field to enter anything though.

**Comment by eoger** [comment]
@RalfJung try flipping the pref I mentioned in my previous comment in `about:config`.

**Comment by RalfJung** [comment]
That's looking pretty synchronized indeed, thanks :D

Is there an upstream bug for stabilizing this API?
