### ISSUE TITLE
History and tabcenter working together

### ISSUE THREAD

**Issue by Enchufadoo** [eoger/tabcenter-redux#236]
I'm trying to deal with the following behaviour. 

When I open the history (ctrl h) the history pane replaces the tabcenter pane, then when I close the history panel by pressing (ctrl h again or closing it with the mouse) the tab center pane doesn't appear back again, 

How do you guys handle this? Thanks.

**Comment by eoger** [comment]
There's not much we can do here, you can press Ctrl+Shift+L to open the Tab Center pane again instead of pressing Ctrl+H

**Comment by Enchufadoo** [comment]
Is that the same shortcut for every OS @eoger? I'm on Windows, and nothing happens.

**Comment by eoger** [comment]
I think some people reported that shortcut as broken, we should try to change it.

**Comment by Enchufadoo** [comment]
@eoger  thanks
