### ISSUE TITLE
Vertical Tabs

### ISSUE THREAD

**Issue by mikelmasek** [eoger/tabcenter-redux#237]
I installed the add-on, but there are no vertical tabs.  I have used this before, but all of a sudden they were no longer there. What am I doing wrong?

**Comment by eoger** [comment]
You have to open the Sidebar again. Either by:

- Clicking on the sidebar <img width="31" alt="screen shot 2017-11-01 at 9 23 40 pm" src="https://user-images.githubusercontent.com/6424575/32305278-fc0d69bc-bf4a-11e7-8535-5e93cf4b263d.png"> button, which should be located near your address bar (if not you can add it using Firefox's Customize feature).

- Going in the menu View -> Sidebar -> Tabs:
<img width="176" alt="screen shot 2017-11-01 at 9 25 12 pm" src="https://user-images.githubusercontent.com/6424575/32305323-4262e130-bf4b-11e7-8458-213d91c0b8bf.png"> .

**Comment by mikelmasek** [comment]
Thanks! 2nd option worked!
