### ISSUE TITLE
Tab management

### ISSUE THREAD

**Issue by rayman89** [eoger/tabcenter-redux#238]
Are there plans to implement tab management features to the extension such as selecting multiple tabs with control or shift + click and do actions for the selected tabs (like closing re arranging them etc)? 
In case you do could you add the option to bookmark selected tabs, to copy the url of the selected tabs and move the selected tabs to a new or existing window? (For existing windows to differentiate them you could name the windows like the active tab they have at the moment).
Could you add a tick box or something like that next to the search box to show duplicated tabs only.

Thanks for your time and for creating the addon.

**Comment by eoger** [comment]
Probably not, I'd like to keep the Tab Center as simple as possible. I think other add-ons like Tree Style Tabs have way more options and do it best.

**Comment by rayman89** [comment]
Trees are confusing and complicated for me =(
