### ISSUE TITLE
hiding vertical white line on the right

### ISSUE THREAD

**Issue by hethhhhh** [eoger/tabcenter-redux#244]
When using the CSS in the examples 

```
#tablist {
  margin-right: -16px; /* Value from KDE's Breeze theme; adjust as needed */
  transition: margin-right 0s 1s;
}

#tablist:hover {
  margin-right: 0px;
  transition: margin-right 0s 4s;
} 
```

I have an ugly white line which doesn't shrink

screenshot: https://i.imgur.com/w7v8oNP.png

**Comment by eoger** [comment]
@dos1 might be able to help, which OS are you using?

**Comment by dos1** [comment]
Just adjust the margin, as the comment says. This line looks like 1 pixel wide, so -17px should do.

**Comment by hethhhhh** [comment]
@eoger I don't believe it's OS related, but how should I know. it's win8.1x64 with dark (dev) theme

@dos1 I tried that of course, it's not working. appears to be some other element, but for the life of me couldn't figure out how to shrink it.

**Comment by Keith94** [comment]
Can you try adding the following to your [userChrome.css](http://kb.mozillazine.org/index.php?title=UserChrome.css) file. This should darken the sidebar's border when using Firefox's dark theme.

```css
#main-window[lwthemetextcolor="bright"] .sidebar-splitter {
  border-right-color: #0C0C0D !important;
}
```

**Comment by hethhhhh** [comment]
@Keith94 that worked, thanks; 
is it possible this to be in the extension in some way? or there is no API for changing that

**Comment by Keith94** [comment]
>there is no API for changing that

Likely this. Extensions can't modify interface things afaik.
