### ISSUE TITLE
Hardcoded hsl format

### ISSUE THREAD

**Issue by noscript** [eoger/tabcenter-redux#245]
Is there any reason why it is done that way:
```css
--tab-background-normal: 0, 0%, 99%;
...
background-color: hsl(var(--tab-background-normal));
```
instead of:
```css
--tab-background-normal: hsl(0, 0%, 99%);
...
background-color: var(--tab-background-normal);
```

It makes themming somewhat complicated, as `0, 0%, 99%` doesn't get recognized by my text editor. Besides it doesn't allow to use e.g. `rgb()` format in `--tab-background-normal`.

Would you accept a PR, fixing this?

**Comment by dos1** [comment]
I already noticed and wanted to change this, but turned out there are some places that use notation like `hsla(var(--tab-background-normal), 75%);`, so I left it as is. My CSS-fu is a bit rusty though, so maybe there's a better way to add opacity to a color from variable these days? :)

**Comment by dos1** [comment]
It's already fixed, isn't it?

**Comment by noscript** [comment]
Looks like it is :)
