### ISSUE TITLE
Highlight tabs that hasn't been loaded.

### ISSUE THREAD

**Issue by fredrikhl** [eoger/tabcenter-redux#246]
I'm coming over from Tab Tree on FF56 to this tab module.

The feature I'm missing the most from Tab Tree in tabcenter-redux, is the ability to highlight tabs that have not been loaded (e.g. after a restart). This allows me to easily identify unvisited tabs that may just be hanging around, and that I really don't need anymore.

**Comment by dos1** [comment]
They are already styled with reduced opacity (and can be restyled with custom CSS), aren't they?

**Comment by jmozmoz** [comment]
Here an example:

```
.tab.discarded {
  font-style: italic;
}
```

**Comment by fredrikhl** [comment]
Huh, is this an issue with FF56, maybe? Applying text-changes to the `.tab.discarded` class does not seem to have any effect…

**Comment by dos1** [comment]
Hah, could be :) Thankfully FF57 releases tomorrow :D

**Comment by eoger** [comment]
@fredrikhl Are you using Tab Center 0.5.3? You check this by click on the gear icon next to the search box.

**Comment by fredrikhl** [comment]
Sorry, been out of the office, so I haven't been able to check.

So, Tab Center Redux was listed as version 0.5.4 now, so I assume I was using 0.5.3. I installed this addon after 0.5.3 was committed in the logs, at least, and have automatic updates checked.

I did however restart Firefox now, entering the post-quantum world, and the tabs are greyed out, the icons transparent, and my custom style (`.tab.discarded { font-style: italic; }` was immediately applied.

So this is either a firefox version issue, or something changed in 0.5.4… Either way, this issue should probably be closed, unless you're aiming for pre-FF57 support.

**Comment by eoger** [comment]
Oh indeed! I always forget that people use other browsers than nightly :)  
Yes this was added in [Bug #1377733](https://bugzilla.mozilla.org/show_bug.cgi?id=1377733) which is now live on 57.
I believe we can close this now, thank you for the report anyway!

**Comment by nydhegg** [comment]
Any possible way to enable .tab.discarded on firefox 56? This styling works in Quantum but not in previous version. This is very distressing.

**Comment by dos1** [comment]
No, it needs Firefox 57.
