### ISSUE TITLE
How can i close and then open the Sidebar again

### ISSUE THREAD

**Issue by lightblue94** [eoger/tabcenter-redux#248]

**Comment by dos1** [comment]
"Sidebars" toolbar button
or
Left Alt -> View -> Sidebar
or
"Library" toolbar button -> History -> View History Sidebar, then switch to Tab Center Redux
or
some keyboard shortcuts, like CTRL+B or CTRL+H.

**Comment by EvanHahn** [comment]
I'm not sure if it's documented, but Ctrl+Shift+O (or ⌘+Shift+O on macOS) opens and closes the sidebar for me.

**Comment by eoger** [comment]
I also added a toolbar button in https://github.com/eoger/tabcenter-redux/commit/a8760b1a165fa81c508fa360a8f266c2a2469d12, feel free to re-open if you still can't open Tab Center Redux :)
