### ISSUE TITLE
Dynamic compact pinned tabs

### ISSUE THREAD

**Issue by kemayo** [eoger/tabcenter-redux#250]
I like compact pinned tabs when I have multiple pinned tabs. However, it's not uncommon for me to only have a single pinned tab in a window, and in that case compact mode looks a bit awkward.

It might be helpful to have an equivalent to the "dynamic" option for compact mode here. In dynamic mode a single pinned tab could continue to show its title, switching to the collapsed icon-only mode as soon as a second pinned tab is added.

**Comment by eoger** [comment]
Thanks for the suggestion! I think you could probably come up with a custom CSS for that, but I don't intend to add that option upstream.
