### ISSUE TITLE
Tab order not configurable

### ISSUE THREAD

**Issue by hoenes1** [eoger/tabcenter-redux#251]
Tabs are always sorted from old to new, making the latest opened tabs appear at the bottom. There should be an option to flip the order, so the latest tabs are displayed at the top of the list.

**Comment by EvanHahn** [comment]
[This CSS tweak](https://github.com/eoger/tabcenter-redux/wiki/Custom-CSS-Tweaks#use-reversed-tab-order-202) will reverse the tab order. Does that solve your problem?

**Comment by hoenes1** [comment]
Yes, that's exactly what I was looking for, thanks.
