### ISSUE TITLE
show/hide vertical tabs on hotkey

### ISSUE THREAD

**Issue by atommixz** [eoger/tabcenter-redux#254]
TST used F1 for this option. I like it. Useful for me. Can u do the same?

**Comment by EvanHahn** [comment]
I'm not sure if it's documented, but Ctrl+Shift+O (or ⌘+Shift+O on macOS) opens and closes the sidebar for me.

**Comment by gooddadmike** [comment]
This should be indicated on the sidebar and also documented in the options. Looking at the manifest also appears the Ctrl Shift L highlights the tab search. Doesn't work for me though.

**Comment by eoger** [comment]
Duplicate of https://github.com/eoger/tabcenter-redux/issues/131, I'll update the add-on description to make it clearer.
