### ISSUE TITLE
Dark theme not rly dark, it's grey

### ISSUE THREAD

**Issue by atommixz** [eoger/tabcenter-redux#255]
U should do dark theme colors like TST used. Current colors looks like 'grey'. I like rly dark theme, like TST used.

**Comment by dos1** [comment]
You can easily customize it by yourself with CSS.
Isn't the default dark theme matching the appearance of Firefox's dark theme?

**Comment by atommixz** [comment]
my default gtk theme is 
local/gtk-theme-united-gnome 1:2.2-2
    GTK2/3 + GNOME Shell theme based on a Ubuntu 18.04 design concept.

And Firefox theme set as "Default". Theme TCR is different. Just a 
![2017-11-17-004018_1920x1034_scrot](https://user-images.githubusercontent.com/359276/32917472-5982e1a8-cb30-11e7-8220-7ddaf1761930.png)
![2017-11-17-004412_1920x1034_scrot](https://user-images.githubusercontent.com/359276/32917503-760e2792-cb30-11e7-89fe-9001065e672c.png)

look.

**Comment by atommixz** [comment]
much better for me now
`body {
    background-color: #000000;
}`

**Comment by Keith94** [comment]
This has been fixed by #321.

**Comment by atommixz** [comment]
Looks usable for me, tnx
