### ISSUE TITLE
Hide tab bar with one tab

### ISSUE THREAD

**Issue by EttoreMiele** [eoger/tabcenter-redux#257]
Hi, as per title I would like to hide the one tab that usually I get when I start Firefox. I used this addon but with the newest version of Firefox is not compatible. Could you help me? 

https://addons.mozilla.org/en-GB/firefox/addon/hide-tab-bar-with-one-tab/

**Comment by Smile4ever** [comment]
This is currently not yet possible with WebExtensions, the technology that Tab Center Redux (and all other recent Firefox addons) use. The implementation of the necessary API is being tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1332447

**Comment by EttoreMiele** [comment]
Thanks a lot for the reply. So it's an ongoing "issue"? It's not a big deal, I will wait an add-on then :)
