### ISSUE TITLE
Ctrl+scroll causes sidebar to zoom

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#260]
### Steps to reproduce
1. Hover the Tab Center Redux sidebar with the mouse.
1. Hold <kbd>Ctrl</kbd> and scroll with the mouse wheel.

Info: https://stackoverflow.com/questions/27116221/prevent-zoom-cross-browser

**Comment by lopis** [comment]
Which OS and which Fx version? I couldn't reproduce this

**Comment by Keith94** [comment]
@lopis Win 10 + Fx 59

**Comment by dos1** [comment]
I can reproduce with Fx59 on GNU/Linux. I think the first time I did it accidentally was after switching from 57 beta to 59 nightly.

**Comment by Lej77** [comment]
Tree Style Tabs just fixed this problem. More info at [Tree Style Tab Issue 1566](https://github.com/piroor/treestyletab/issues/1566).

**Comment by allixx** [comment]
I don't know how correct this solution is, but adding this listener to tablist.js / SideTabList / setupListeners works for me:

    window.addEventListener("wheel", (e) => {
        if (e.ctrlKey || ('keyCode' in e && e.keyCode == e.DOM_VK_CONTROL)) {
            e.preventDefault();
        }
    });

**Comment by zeroibis** [comment]
Just noticed this issue, unfortunately ctrl+0 does not cause the zoom level to reset. Luckily, restarting firefox does.
