### ISSUE TITLE
F1 keyboard shortcut does not work under Linux

### ISSUE THREAD

**Issue by jronallo** [eoger/tabcenter-redux#261]
The readme states that the `F1` keyboard shortcut can be used to toggle the tab center sidebar, but it has no effect.

**Comment by jronallo** [comment]
I was probably trying this before https://github.com/eoger/tabcenter-redux/commit/396033bf7c3d6596660cf7fd1a70f6574bd2f161 was released.

**Comment by eoger** [comment]
I'll do a quick release.
