### ISSUE TITLE
Hotkey conflicts with "Sort Tabs by URL" add-on

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#262]
The Sort Tabs by URL add-on ([AMO](https://addons.mozilla.org/addon/sort-tabs-by-url/)/[GitHub](https://github.com/andymckay/sort-tabs-by-url)) uses the same <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>O</kbd> hotkey which makes Tab Center's hotkey inoperative. :( Is there any workaround for that besides editing the manifest.json?

**Comment by eoger** [comment]
Nope, it's a bit unfortunate, your best bet is to plead your case to the addon developer or make your own fork. [Related bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1303384).

**Comment by Keith94** [comment]
Ok thanks.

**Comment by eoger** [comment]
Quick update: work in [under way](https://bugzilla.mozilla.org/show_bug.cgi?id=1421811) to allow users to update commands hotkeys.
