### ISSUE TITLE
Pinned about:addons page lost its favicon

### ISSUE THREAD

**Issue by Rictusempra** [eoger/tabcenter-redux#264]
Environ. Firefox 58.0b4, Tab Center Redux 0.5.5, Windows 10.16299.64 Pro

![image](https://user-images.githubusercontent.com/16912240/32997965-b76d8af4-cdd1-11e7-9c1e-aee8d152fa6e.png)

**Comment by eoger** [comment]
This is probably a duplicate of https://github.com/eoger/tabcenter-redux/issues/10

**Comment by Rictusempra** [comment]
Seems to be a Firefox bug?
https://bugzilla.mozilla.org/show_bug.cgi?id=1403620

**Comment by Rictusempra** [comment]
Yes, it is a dup
