### ISSUE TITLE
Use light variant of icon for dark themes

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#266]
The new toolbar button (a8760b1) appears too dark when using a dark theme in Firefox.

~~Apparently the API [management.getAll()](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/management/getAll) can help with determining the theme and selecting the proper icon.~~

**Comment by dos1** [comment]
I think this API might be better suited: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/theme :)

**Comment by eoger** [comment]
I think what we want is checking the "dark theme" pref + [browserAction.setIcon](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browserAction/setIcon) .

**Comment by Keith94** [comment]
I tested the fix e0c87c4: Looks good with the dark theme, but with "Space Fantasy" theme, it looks too dull.

![firefox_2018-03-29_20-10-20](https://user-images.githubusercontent.com/5490615/38123001-45de8d86-33c8-11e8-979e-9f0cfc12cb29.png)
