### ISSUE TITLE
How to change the tab sidebar color?

### ISSUE THREAD

**Issue by jrw** [eoger/tabcenter-redux#267]
Besides "normal" and "dark" themes, I mean.  Can you add one more tip?  Thank you!!

**Comment by eoger** [comment]
If you're fluent with CSS, you can create your own theme since Tab Center Redux has a "Custom Stylesheet" feature :)

**Comment by jrw** [comment]
Unfortunately, I'm not fluent in CSS.  I was hoping that a short tip like #sidebar-box { background-color: something; } would work.  I'd tried a few things, but couldn't find the right tags to use.  Neither of the normal and dark themes allows me to easily distinguish the sidebar from my surrounding desktop (dark) and the main browser window (light/white), so I was going to try playing a bit with different colors.  I like your tips - they're very helpful and they allow you to avoid a complicated bunch of menu choices which may be overkill.  But I was hoping to avoid adding the complication of adding an entire theme.  If that's not possible, maybe I'll end up going the theme route

**Comment by allixx** [comment]
https://github.com/eoger/tabcenter-redux/blob/master/src/tabcenter.css#L782

you can try copypasting everything below that line to "Cystom Stylesheet" editbox, and modifying it to your taste. and yeah, enable Dark theme since you'll be overriding it.

**Comment by jrw** [comment]
Thank Edouard, I'll try that!  
I have to restart Firefox each time I change something, right?  (I wonder if there is there an easy way to do that?)

**Comment by allixx** [comment]
css overrides in "Custom Stylesheet" are immediate.

**Comment by jrw** [comment]
Enabling Dark theme and then adding this to the Custom Stylesheet worked!  Thanks for your help (maybe make this a "Tip"):
body.dark-theme { --tab-background-normal: 222, 20%, 40%; }

**Comment by eoger** [comment]
Anytime!

**Comment by jrw** [comment]
I'm still using tabcenter-redux on all my machines (Linux, Windows) and enjoying it.  Thanks!

**Comment by jrw** [comment]
Fixed by:
  body.dark-theme {
    --tab-background-normal: hsl(222, 20%, 40%);
    --tab-background-active: hsl(221, 50%, 50%);
    --close-button-color: hsl(rgba(238, 238, 241, .25));
    --close-button-hover: hsl(rgba(238, 238, 241, .55));
  }
