### ISSUE TITLE
[Feature request] Add tab title change notification indicator

### ISSUE THREAD

**Issue by sabi0** [eoger/tabcenter-redux#268]
When GMail receives a new email it changes the page title. And that triggers Firefox to show a notification "light" on the GMail tab: https://stephentvedt.com/2012/09/17/firefox-pinned-tab-notifications/

This is very useful for compact pinned tabs.
And unfortunately Tab Center Redux does not show such notifications yet.

**Comment by allixx** [comment]
not exactly a solution you're looking for, but you can enable "Unread message icon" addon in gmail's Labs to display unread messages count on gmail page icon.

**Comment by sabi0** [comment]
GMail was just an example. I also have other pinned tabs I want to have notifications for, e.g. Telegram.
Thanks for the tip anyway.

**Comment by Keith94** [comment]
I think the API needs to be added first. See https://bugzilla.mozilla.org/show_bug.cgi?id=1396684

**Comment by sabi0** [comment]
Well, Tree Style Tabs developers apparently found some workaround then.
Would it be possible to simply detect title changes until the proper "attention" access API lands?
(e.g. in the tab.js updateTitle() method)

**Comment by eoger** [comment]
Yup it should be easy enough to do, at least for the title changes.
