### ISSUE TITLE
css for custom thumbnail size?

### ISSUE THREAD

**Issue by RonConescu** [eoger/tabcenter-redux#269]
Folks,

I love this extension; thank you for this inspired work.

Is there a way to change the thumbnail (preview) size through CSS?

I've been scanning through the code for a while, and experimenting, but I haven't yet found the class/id/tag which uniquely lets me access the thumbnail.

For that matter, is there a complete list of all customizable CSS in the project?

If this issue is a duplicate, my humble apologies.  (I've also been searching the issues for a while.)

Thank you!

Ron

**Comment by eoger** [comment]
You're looking for `.tab-meta-image`, best way to find these classes is to debug the addon by opening `about:debugging` and then you can inspect the whole document live.

**Comment by RonConescu** [comment]
Edouard,

Thank you, very much, for those clues. I'm having trouble making them work:

1) See attached screen shot 1. When I change the width for `.tab-meta-image`, the container view seems to stretch, but the image itself does not.  Can you tell me what else I should be doing?

2) See attached screen shot 2. Having enabled add-on debugging, opened the Developer Tools for Tab Center Redux, and expanded every element in the document, I don't see anything that seems to correspond to the tabs or their previews. The screen shot tries to illustrate that I opened a tab for yahoo.com, but can't find it in the document inspector. Searching and visually inspecting for "tab-meta-image" similarly shows nothing.

Can you help me further?

Ron

![shot 1 - css not working](https://user-images.githubusercontent.com/5509706/33299236-8faa3df4-d39f-11e7-8cbc-0987f852c747.png)

![shot 2 - can t find content in document](https://user-images.githubusercontent.com/5509706/33299237-8fc12e24-d39f-11e7-8279-05a47242c4eb.png)

**Comment by eoger** [comment]
You probably want to play with the `background-*` properties, which will be easier with the inspector.
On screenshot 2, I'm seeing that you are debugging the "background" page, to switch to the sidebar page you have to press the button on the top right of the inspector then select /tabcenter.html

<img width="490" alt="screen shot 2017-11-27 at 9 26 20 pm" src="https://user-images.githubusercontent.com/6424575/33299455-b6a5b77a-d3b9-11e7-9e25-08026d77dae3.png">

**Comment by eoger** [comment]
Hope you find what you wanted, closing!
