### ISSUE TITLE
Use more subtle tab close button

### ISSUE THREAD

**Issue by sabi0** [eoger/tabcenter-redux#270]
Here is Firefox native tab close button
![image](https://user-images.githubusercontent.com/11509875/33309579-d215853e-d41e-11e7-9237-7a193f74d817.png)

Compare it to Tab Center Redux much heavier one:
![image](https://user-images.githubusercontent.com/11509875/33309614-f74e470a-d41e-11e7-9b0d-409aac37dac6.png)

**Comment by allixx** [comment]
`/* resize the close icon */
.tab-close {
  height: 10px !important;
  width: 10px !important;
}`

**Comment by Keith94** [comment]
Yeah, I find Tab Center Redux's close button very prone to misclicking due to size and appearance. Having a native look and feel by default would look better and probably reduce the number of errors/misclicks.

**Comment by Keith94** [comment]
Fixed by #328.
