### ISSUE TITLE
Feature Request: Setting to disable Container Tabs?

### ISSUE THREAD

**Issue by clobber** [eoger/tabcenter-redux#272]
`contextualIdentities` is required in permissions which forces use of Container Tabs, which cannot be disabled in about:preferences.

<img width="678" alt="screen shot 2017-11-29 at 12 16 52 am" src="https://user-images.githubusercontent.com/1303132/33360750-baceeea2-d49a-11e7-8d82-0df440b3e873.png">

I don't like the added menu items this brings, so it'd be nice to have a way to disable them without messing with privacy.userContext.* in about:config.

**Comment by eoger** [comment]
Sorry we can't really touch permissions at runtime. This permission is specified in a .json file:
https://github.com/eoger/tabcenter-redux/blob/master/src/manifest.json#L18
Your best bet is to fork Tab Center Redux :)
