### ISSUE TITLE
[Feature Request] Tab groups

### ISSUE THREAD

**Issue by katzelad** [eoger/tabcenter-redux#274]
The pre-WE Tab Center was originally supposed to include tab groups functionality (It was in one of their sketches), are there any plans to do this in the future? It would be extremely useful since there is no reliable tab groups extensions for 57+.
BTW, this is the best tab sidebar extension,
Thanks!

**Comment by Keith94** [comment]
Author says he won't implement this for now (#36)

But you can try something like 'Simple Tab Groups': https://addons.mozilla.org/addon/simple-tab-groups/

**Comment by eoger** [comment]
Thanks, sorry about the change of heart in that bug by the way, I realized I wanted to keep Tab Center as vanilla looking/simple as possible a bit later.

**Comment by youk** [comment]
It would be nice if there was a way to place Simple Tab Groups button onto Tab Center Redux toolbar. Is this at all possible?

**Comment by katzelad** [comment]
Simple Tab Groups is not good enough because it unloads the tabs in inactive groups (since tab hiding is currently impossible for WE).
It would be nice to have a tab group option only for Tab Center, which allows categorizing tabs in the sidebar while keeping all of them loaded in the main tab bar, removing the need to unload them.
No extension currently has this functionality AFAIK.

**Comment by youk** [comment]
> Simple Tab Groups is not good enough because it unloads the tabs in inactive groups (since tab hiding is currently impossible for WE).

Uh? It is good enough as current state of API allows. Required API is already there in Firefox 59 and tab hiding in related extension will follow.
