### ISSUE TITLE
"Close Other Tabs" and "Close Tabs Underneath" options do not warn users and close tabs directly

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [eoger/tabcenter-redux#275]
[Affected versions]:
- Firefox 57 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Tab Center Redux was previously installed on a clean new Firefox profile.
- Tab sidebar is opened.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Open more than 2 tabs.
3. Right click one of the tabs from the sidebar.
4. Click the "Close Other Tabs" option.
5. Observe the behavior.

[Expected results]:
- A dialog box appears asking the user if he is sure that he wants to close "x" tabs.

[Actual results]:
- All other tabs are closed.

[Notes]:
- The issue is also reproducible with the "Close Tabs Underneath" option.
- The issue is not reproducible if I choose the same option from Firefox's own tab strip.
- Attached a screen recording of the issue:
![close other tabs does not warn users](https://user-images.githubusercontent.com/18304511/33549116-1ea02da0-d8f2-11e7-8a55-0af581e3b2ba.gif)

**Comment by Keith94** [comment]
Dupe of #93?

>Web Extensions have no way of reading Firefox preferences.

**Comment by SoftVision-CiprianMuresan** [comment]
More than likely, thanks for pointing that out.
