### ISSUE TITLE
Show / Hide Tab Sidebar button

### ISSUE THREAD

**Issue by dwt** [eoger/tabcenter-redux#280]
I would really like to show / hide the tab sidebar quickly, to free up screen real estate.

The most discoverable way to implement this, is IMO a button in the standard toolbar (which can be turned off via the standard customize window.

Is this possible? Can you please add it?

**Comment by dwt** [comment]
Also a shortcut would probably have to be operation system specific, which I don't know is so easy.

**Comment by Smile4ever** [comment]
This has already been implemented, please look closely on the toolbar or right click the toolbar -> Customize and add the button.

**Comment by dwt** [comment]
Ahh.... Now I feel dumb. :-)

Thanks!
