### ISSUE TITLE
Hide with one Tab

### ISSUE THREAD

**Issue by qoheniac** [eoger/tabcenter-redux#289]
Is it possible (maybe via css) to hide the side bar if there's only one tab?

**Comment by Smile4ever** [comment]
Duplicate of https://github.com/eoger/tabcenter-redux/issues/168

**Comment by Keith94** [comment]
I added a workaround here: https://github.com/eoger/tabcenter-redux/wiki/Custom-CSS-Tweaks#hide-sidebar-with-only-one-tab-open
