### ISSUE TITLE
Tab bar isn't present in private window by default

### ISSUE THREAD

**Issue by kengho** [eoger/tabcenter-redux#290]
Hello! Thanks for great add-on! Here's the "bug":

**Steps to reproduce:**

1. Install and open fresh Firefox 57 (tested Firefox 57.0.3@Windows 7 x64 and Firefox 57.0.1@KDE Neon x64).

2. Open private window.

**Expected behavior:**

- Tab center shows tabs.

**Actual behavior:**

- Tab center isn't present and you should use hotkey to reach it.

Considering fairly questionable choice for default hotkey on Linux (F1), which could be (and, as fact, in most distributions, is) already taken, browsing tabs in private window with hidden native tab bar on top is uncomfortable.

I don't know, is there are reasons for this behavior, maybe I missing something, but it seems inconvenient.

**Comment by dos1** [comment]
I'm workarounding this by not hiding the native tab bar in private windows. Check out the Plasma Breeze CSS for that.

**Comment by tze** [comment]
+1 from me. This is really annoying.

**Comment by eoger** [comment]
Yeah it sucks :(
Sadly I can't do much about it on the extension side, [here's the Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1418772).

**Comment by tze** [comment]
This has been resolved in Firefox. I think this issue can be closed.
