### ISSUE TITLE
Make a new AMO release

### ISSUE THREAD

**Issue by dos1** [eoger/tabcenter-redux#292]
There was no new release on AMO since November. My CPU is struggling with rendering the animated loading throbbler each time some page is being loaded :(

It would be a great relief if the recent commits would finally be released to the browsers in the wild out there.

**Comment by eoger** [comment]
Done, sorry I haven't had time to work/review PR on Tab Center recently. I'm also working on a refactor of the code in the background.

**Comment by dos1** [comment]
Thanks a lot! :)
