### ISSUE TITLE
Address bar not focused when opening a tab (Activity Stream enabled)

### ISSUE THREAD

**Issue by eoger** [eoger/tabcenter-redux#3]
Not sure if this is a WebExtensions bug or not, some investigation required (recreate a minimal test-case).

**Comment by eoger** [comment]
Looks like this only happens when Activity Stream is enabled. Since it is behind a pref at the moment and the development is still going under way, let's P3 that.

**Comment by Keith94** [comment]
I can't seem to reproduce with Activity Stream 1.13. Opening new tab focuses address bar correctly.

**Comment by Keith94** [comment]
Okay, I just found a similar bug... if you open a new tab it focuses the address bar, but if you select another tab, then select the new tab you opened before, address bar is no longer focused as it should be.

**Comment by eoger** [comment]
Let's close this, the main issue has been fixed here.
