### ISSUE TITLE
Incorrect tab preview icon used after closing private browsing window

### ISSUE THREAD

**Issue by hafta** [eoger/tabcenter-redux#30]
Steps to reproduce:

1. Have one regular window open with multiple tabs.
2. Open new private browsing window and load a web page in it.
3. Close private browsing window.

Actual result:
The tab preview icon from the web page loaded in step 2 is displayed on the tab in the original window.

Expected result:
Tab icons in the original window are not changed.

**Comment by eoger** [comment]
Good find, I'm probably forgetting to check for the window ID somewhere.
