### ISSUE TITLE
"Close Tabs Underneath" ignores filter

### ISSUE THREAD

**Issue by dfaerch** [eoger/tabcenter-redux#303]
Say you open 3 tabs only. 
* Set the 2 topmost tabs to github.com and the bottom one to something else.
* Filter tabs using the search string "github". Now you only see the the 2 github tabs. 
* Select the topmost tab and right click -> choose "Close Tabs Underneath".

As expected, the github tab below gets closed. But removing the filter, you see that the bottom non-github tab has also been closed.

I think its natural to expect items from the right-click menu, to work only on the visible tabs, rather than closing things in the "background".

**Comment by Keith94** [comment]
Agreed. I noticed this bug as well.
