### ISSUE TITLE
Refactor SideTabList to be more explicit about positioning.

### ISSUE THREAD

**Issue by thomcc** [eoger/tabcenter-redux#315]
Right now the position is implicitly the same as the DOM. This makes a number of features harder, and makes certain things more complex and slower than they should be.

I'd like to wait for my outstanding PRs to get merged before this, however.

**Comment by eoger** [comment]
This is somewhat connected to https://github.com/eoger/tabcenter-redux/issues/296 since the DOM may have holes now.

**Comment by eoger** [comment]
Fixed by https://github.com/eoger/tabcenter-redux/commit/41128b108c0b7d4a45748009ac5abd28bd289cf2!
