### ISSUE TITLE
Context menu can't overlay content

### ISSUE THREAD

**Issue by rnewman** [eoger/tabcenter-redux#32]
I'm pretty sure this is a Firefox limitation, but capturing it here for now.

<img width="287" alt="screen shot 2017-06-15 at jun 15 07 25 54" src="https://user-images.githubusercontent.com/91722/27186027-abd05374-51d6-11e7-82e2-96b78b88751e.png">

**Comment by eoger** [comment]
I implemented a workaround in https://github.com/eoger/tabcenter-redux/commit/49dba6b284732e76b157f62c2d28ed39c4e3051e, I'll try to post an update to AMO before the end of the week.
