### ISSUE TITLE
Add support for closing tab with double-click

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#327]
[Bug 1435142](https://bugzilla.mozilla.org/show_bug.cgi?id=1435142) was fixed, so now we can close a tab by double-clicking on it. Feature is controlled via the `browser.tabs.closeTabByDblclick` pref. So, I think TCR should have that feature too.

**Comment by eoger** [comment]
`browser.browserSettings.closeTabsByDoubleClick` exposes that setting to webextensions. I'd be happy to mentor someone to work on this!

**Comment by d53dave** [comment]
I'd like to contribute this feature. Could you give me some tips on where to start? It's been a while since I've worked with JS professionally, but I'm positive it's going to be fine.
