### ISSUE TITLE
Consider integrating Sea Containers functionality

### ISSUE THREAD

**Issue by jonathanKingston** [eoger/tabcenter-redux#33]
It's my belief that functionality provided by [Sea Containers](https://addons.mozilla.org/en-GB/firefox/addon/sea-containers/) is very useful for users with containers. However I don't have design time for it etc.

Core functionality:

- Easy access to create a new tab of each containers
- Hide away other containers depending on the current container
- Easy access to pinned tabs per container
- Tab count per container making multiple windows easier to identify

I have an experimental branch that searches all tabs and expands the relevant containers.

I considered putting the current container in a select box at the top however the easy access to the new tab of all containers is pretty core in improving containers usability.

Implementing this without changing the current UI for non container users might be a hard task.

**Comment by eoger** [comment]
I guess we could implement a button behind a pref that filters tabs depending on their container.
Implementing every feature is probably out of scope, I'd like to keep the addon as vanilla as possible.

**Comment by grahamperrin** [comment]
If Sea Containers functionality will be integrated, then – if/when there arises a WebExtensions successor to Tab Groups – it will be desirable to integrate additional functionality, some of which will be contrary to the essence of (Sea) Containers. 

So, with respect, 

> … keep the addon as vanilla as possible.

👍
