### ISSUE TITLE
Some testing stuff in the latest release (0.6.2)

### ISSUE THREAD

**Issue by hooloovoo79** [eoger/tabcenter-redux#340]
I think some of your testing stuff or build environment or something has made it into the latest release. 0.6.2 is ~4X larger than the last release, and the commits don't seem to have added any real large code parts and there is now a test folder in the extension. Just figured I would let you know.

**Comment by eoger** [comment]
Ah yes I forgot to strip it, I'll make a new release. Thanks!

**Comment by eoger** [comment]
Version 0.6.3 released.
