### ISSUE TITLE
Breeze-Theme: White background after update

### ISSUE THREAD

**Issue by mcdax** [eoger/tabcenter-redux#341]
I'm a big fan of the Breeze-Theme (configed as described in the Wiki).
Unfortunately the background color has changed to white after the last add-on update although I haven't changed the Stylesheet.

**Comment by dos1** [comment]
Thanks for pinging! The color variables has changed in the addon and now need to be wrapped with `hsl()`. From a quick glance into code it seems like that should be just it. I have updated the wiki page :)

**Comment by eoger** [comment]
Awesome thank you!
