### ISSUE TITLE
Last update (30 April 2018) is broken

### ISSUE THREAD

**Issue by unclechu** [eoger/tabcenter-redux#342]
After last update I just see empty black space instead of tabs list.
![screenshot from 2018-04-30 19-14-39](https://user-images.githubusercontent.com/799353/39431627-bd0f17c2-4caa-11e8-8dde-ea76bac3dd8f.png)
![screenshot from 2018-04-30 19-15-31](https://user-images.githubusercontent.com/799353/39431671-dd895fbc-4caa-11e8-8ba4-4c7a9cadd614.png)

**Comment by unclechu** [comment]
Reinstalling (removing and installing it again) haven't helped.

**Comment by Smile4ever** [comment]
Do you see errors in the browser console?

**Comment by unclechu** [comment]
Forgot to mention version of my browser: `Firefox Quantum 57.0.1 (64-bit)`.

**Comment by unclechu** [comment]
@Smile4ever just on any page? Nothing specific to this plugins (on https://www.haskell.org/ for example it's empty.

**Comment by eoger** [comment]
Can you go to `about:debugging`, look for Tab Center Redux and press the Debug button (you might have to check "Enable add-on debugging" at the top of the page)? This will open the addon console.
I'm guessing we're using an API that isn't supported on 57.

**Comment by unclechu** [comment]
@eoger here is what I see there when I open plugin's window:
```
[Exception... "Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsIMessageSender.sendAsyncMessage]"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: resource://gre/modules/ExtensionUtils.jsm :: sendAsyncMessage :: line 505"  data: no]  (unknown)
[Exception... "Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsIMessageSender.sendAsyncMessage]"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: resource://gre/modules/ExtensionUtils.jsm :: sendAsyncMessage :: line 505"  data: no]  (unknown)
TypeError: browser.theme.onUpdated is undefined[Learn More]  bundle.js:155:1
```

**Comment by unclechu** [comment]
And also in expanded exception's trace:
```
sendAsyncMessage resource://gre/modules/ExtensionUtils.jsm:505:51
_handleMessage/deferred.promise< resource://gre/modules/MessageChannel.jsm:774:9
```

**Comment by eoger** [comment]
Feel free to pull the code from master, I'll make a new build sometimes this week.
