### ISSUE TITLE
Tabs color broken in 0.6.3

### ISSUE THREAD

**Issue by jrw** [eoger/tabcenter-redux#343]
I had previously used this custom css, based on suggestions from eoger (with Dark Theme):
body.dark-theme {
  --tab-background-normal: 222, 20%, 40%;
  --tab-background-active: 221, 50%, 50%;
  --close-button-color:  rgba(238, 238, 241, .25);
  --close-button-hover: rgba(238, 238, 241, .55);
}

But updating to 0.6.3, this breaks that css for some reason and my tabs now look like:
![tcr](https://user-images.githubusercontent.com/234294/39440884-545fc274-4c7a-11e8-92fe-ed2414aea21a.jpg)

If I disable my custom css, it looks like:
![tcr2](https://user-images.githubusercontent.com/234294/39441100-d27e3500-4c7a-11e8-8cbc-84e4795a5b4d.jpg)

Not sure how to change my custom css to match the latest 0.6.3 changes.

**Comment by Smile4ever** [comment]
Did you try this?

```
body.dark-theme {
--tab-background-normal: hsl(222, 20%, 40%);
--tab-background-active: hsl(221, 50%, 50%);
--close-button-color: hsl(rgba(238, 238, 241, .25));
--close-button-hover: hsl(rgba(238, 238, 241, .55));
}
```

**Comment by jrw** [comment]
No, but I did just now and it works; thanks!

**Comment by jrw** [comment]
Also worked on Linux, but not initially for some reason (but after a few restarts?).
