### ISSUE TITLE
Reordering tabs via extension breaks tab hiding

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#347]
## Steps to reproduce

1. Install [Simple Tab Groups (experimental)](https://addons.mozilla.org/addon/experimental-simple-tab-groups/) and [Order Tabs by Domain](https://addons.mozilla.org/addon/order-tabs-by-domain/)
1. Create two tab groups each containing various tabs
1. Order tabs via domain via the toolbar button

## Expected results
Hidden tabs from other groups should not appear

## Actual results
Hidden tabs from other groups appear in the sidebar

Screen capture:

![2018-05-13_17-10-38](https://user-images.githubusercontent.com/5490615/39973130-c39cc7e4-56d0-11e8-9ffe-970e2ea1263c.gif)

**Comment by Smile4ever** [comment]
Seems to be caused by https://github.com/eoger/tabcenter-redux/blob/5c968e03e109c515f4ee441e9a64ab1bfb202000/src/sidebar/tablist.js#L125-L140

which does not take the "hidden" property into account.

**Comment by Keith94** [comment]
Nice detective work! I hope that's an easy fix.
