### ISSUE TITLE
Add support for tab warming

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#349]
Being somewhat of a new feature, I'm not sure if the API is available to WebExtensions; however, it would be nice to have it implemented if possible.

See https://mikeconley.ca/blog/2018/01/11/making-tab-switching-faster-in-firefox-with-tab-warming/

**Comment by ariasuni** [comment]
There’s no way to trigger this from a WebExtension, but there’s [a bug about it](https://bugzilla.mozilla.org/show_bug.cgi?id=1402256).

It’s labeled «UNCONFIRMED bug which will not be worked on by staff, but a patch will be accepted», so we have to wait for somebody to implement the feature in Firefox.

**Comment by Keith94** [comment]
Darn, I guess we have to wait a while. Thanks for the info @ariasuni
