### ISSUE TITLE
Address bar focus lost when navigating away from new tab

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#352]
## Steps to reproduce
1. Open two new tabs in sidebar
2. With 2nd new tab selected, select the 1st new tab with mouse click

## Actual results
Address bar not focused

## Expected results
Address bar should retain focus

**Comment by Keith94** [comment]
I guess this is a bug in Firefox.

Since TCR is treated the same as any other sidebar, mouse clicks will always remove focus.

**Comment by haarp** [comment]
But it's possible to transfer focus to the address bar from an addon, so this could still be worked around.

**Comment by Keith94** [comment]
Which add-on?

**Comment by haarp** [comment]
I meant extension. Since a double-click on the Tabcenter sidebar opens a new tab *and* redirects focus to the address bar, I figured this should be possible. Or is it Firefox itself that does this?
