### ISSUE TITLE
Owner tab not selected when closing new tab

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#353]
The _select owner on close_ behavior works in most cases, such as searching text with Google or clicking TCR's settings button and closing that tab; however, the behavior is **broken** when closing a new tab.

## Steps to reproduce
1. Make sure `browser.tabs.selectOwnerOnClose`=`true`
1. Have at least two tabs open
1. Select the first tab
1. Click the new tab button in Tab Center Redux
1. Click the close button on the new tab

## Actual results
Second tab gets focus

## Expected results
Owner tab (first tab) gets focus

**Comment by eoger** [comment]
I would be that we need to pass `openerTabId` to `browser.tabs.create`

**Comment by Keith94** [comment]
https://framagit.org/ariasuni/tabcenter-reborn/commit/a78ebfd64439dafd175ffea3249cac892f062771
