### ISSUE TITLE
Tab list should not scroll when pinning a background tab

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#356]
Maybe related to #278.

When pinning a background tab, there's no need to scroll the list to the top because the tab is always visible anyway.

## Steps to reproduce
1. Open many tabs so the tab list overflows
1. Scroll to bottom of tab list
1. Right click -> Pin a background tab

## Actual results
Tab list scrolls to top

## Expected results
Don't scroll

**Comment by Keith94** [comment]
Hi @eoger 

I can still reproduce the issue sometimes with the latest code.

![2018-05-21_13-27-37](https://user-images.githubusercontent.com/5490615/40328379-fdebaa7a-5cfa-11e8-845a-24e87437f8a5.gif)

**Comment by eoger** [comment]
I'll have a look soon

**Comment by Keith94** [comment]
Hi @eoger. Has there been any progress on this? 😃
