### ISSUE TITLE
Duplicated tab should get focus immediately

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#358]
![2018-05-21_13-13-19](https://user-images.githubusercontent.com/5490615/40327753-e4d4eeb8-5cf8-11e8-985c-f983277bc60d.gif)

**Comment by Keith94** [comment]
Seems like Tab Center waits for loading to complete before selecting the tab.

**Comment by ariasuni** [comment]
See here for the bug on Mozilla’s side:
https://bugzilla.mozilla.org/show_bug.cgi?id=1394376

Tree Style Tab uses a workaround involving a lot of their own code. See the bug report:
https://github.com/piroor/treestyletab/issues/1437#issuecomment-334952194

**Comment by Keith94** [comment]
@ariasuni Thanks for the info.

**Comment by ariasuni** [comment]
I made a fix upstream and it was merged. The change will be released with Firefox 68.

https://bugzilla.mozilla.org/show_bug.cgi?id=1394376

**Comment by Keith94** [comment]
Cool! Thnx
