### ISSUE TITLE
"Close Tabs Underneath" ignores filter (recurring)

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#360]
The fix introduced in #307 does not seem to work for me; in fact, I lost data due to accidental closing of tabs. 
I made a screencast just in case it helps prove my point.

![2018-05-22_00-01-02](https://user-images.githubusercontent.com/5490615/40347038-a5acd2b8-5d53-11e8-8456-da8369dea486.gif)

**Comment by dfaerch** [comment]
i can confirm the issue from @Keith94 

I posted the issue #303, which references #307 as the fix (and thank you @eoger for that one). 
But i have 0.6.3 installed in the browser and i still have the same issue. So unless #307  hasn't made it to http://addons.mozilla.org/ yet, the fix didn't solve the issue.

**Comment by Keith94** [comment]
Thanks. That fix was added in [0.6.0](https://addons.mozilla.org/en-GB/firefox/addon/tab-center-redux/versions/?page=1#version-0.6.0), so it must not be working correctly.
