### ISSUE TITLE
"Loading" indicator uses enormous amounts of CPU (recurring)

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#385]
Like in #243, I get very high CPU usage (~60%) whenever a loading spinner is present. Once it's done, CPU goes back down to 5-7%. It's a very critical problem for me because it affects every page load. Any chance of a fix or at least a workaround?

**Comment by dos1** [comment]
My workaround, reducing the animation FPS to 20:
```
.tab.loading .tab-icon::before {
    animation: tab-throbber-animation 1.05s steps(20) infinite;
}
```

**Comment by RalfJung** [comment]
This is still a problem with Firefox 68.0b8 and Tab Center Redux 0.7.1.

Also see https://github.com/piroor/treestyletab/issues/1384#issuecomment-347713777. Seems like Firefox still can't handle animations very well that do not specify a "0% value"?

**Comment by RalfJung** [comment]
So, was there a fix?

**Comment by Keith94** [comment]
#421
