### ISSUE TITLE
Icon in sidebar header/dropdown is hard to see

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#392]
![45795456-aa938400-bc50-11e8-92c7-b5b7de8a077a](https://user-images.githubusercontent.com/5490615/46117116-53dbfc00-c1b4-11e8-82d5-3be43af0460a.png)

**Comment by ariasuni** [comment]
The icon displayed in the header bar and in the list is the same, but with the default dark theme of Firefox, one’s white and the other dark, and we can’t really know what’s the currently used color for each (except if I’m missing something?).

The best fix I can see is to make an icon that works both on light and dark backgrounds.
