### ISSUE TITLE
favicons or thumbnails?

### ISSUE THREAD

**Issue by rinaldi6109** [eoger/tabcenter-redux#411]
I've two Firefox profiles and I've installed TabCenter Redux on both them.
The addon appearance is different using one profile or using the other one.
In the former case, in the sidebar I see the favicon of each opened tab, while in the latter I see the thumbnail.
I don't understand how to force the addon to not show the thumbnail but only the favicon.

**Comment by ariasuni** [comment]
Are you speaking about the fact that when you have a small number of tabs, you see (mostly) the thumbnails but otherwise you only see the favicon? If yes, it can be controlled with the «compact mode» option on the extension’s preferences page.

**Comment by rinaldi6109** [comment]
Well done! Thank you.
