### ISSUE TITLE
Access your data for all websites

### ISSUE THREAD

**Issue by subsign** [eoger/tabcenter-redux#415]
Hey Edouard, is there a reason why 'Access your data for all websites' permission is required?

From what I've read, it's the permission request for [<all_urls>](https://github.com/eoger/tabcenter-redux/blob/699694ff0ebdc0cc06a5c3a1318c6e4519df663e/src/manifest.json#L18). After further reading I arrived at the same question over at [TST](https://github.com/piroor/treestyletab/issues/1536).

What is it in particular that's utilising that permission?

Thanks!

**Comment by dos1** [comment]
Isn't that required for thumbnails?

**Comment by subsign** [comment]
> Isn't that required for thumbnails?
Looks like it, yeah. I'll close this off.
thanks!
