### ISSUE TITLE
Sidebar requires focus, and focus of sidebar prevents interaction with content window.

### ISSUE THREAD

**Issue by kdashg** [eoger/tabcenter-redux#417]
This seems to be a focus issue. When the browser content pane is focused, nothing in the sidebar responds to hover, but clicking on the sidebar seems to focus it, but now while hover and click work in the sidebar, I can't interact (or even return focus to) the browser content pane. The only way to restore interactivity to the content pane is to use the sidebar or main tab bar to change tabs.

Additionally, after changing tabs with the sidebar, the sidebar can't be focused-on for about 10 seconds. I can't figure out what the exact criteria is.

Since it looks like this extension hasn't been updated recently, this regression was likely triggered by a change to Firefox.

**Comment by mnoorenberghe** [comment]
This is https://bugzilla.mozilla.org/show_bug.cgi?id=1536730 with a patch in progress

**Comment by kdashg** [comment]
The browser bug is fixed as of Mar22 nightly!
