### ISSUE TITLE
Right clicking tab brings up wrong context menu Bug

### ISSUE THREAD

**Issue by Jtasiu** [eoger/tabcenter-redux#420]
@eoger

In the latest beta version of firefox whenever I right click a tab it brings up the normal right-click context menu of firefox with functions like view page source as well as the context menu of the addon functions like close tab. It's a major annoyance and I'm guessing something changed on firefox side to cause this.

Is there any solution for this?

**Comment by Jtasiu** [comment]
I think it's a firefox bug so I'll close. I can't find solution to this so please post if you know how to fix it.

**Comment by uahim** [comment]
@Jtasiu how did you get that fixed?

it happens in the latest ESR version, too, so I'm curious.

**Comment by uahim** [comment]
no one?
