### ISSUE TITLE
New tab opened from pinned tab is hidden when using long tab lists

### ISSUE THREAD

**Issue by d53dave** [eoger/tabcenter-redux#429]
Hi,

It's challenging to find a concise title for this, so please bear with me. This is a small issue that has been bugging me so I'm gonna leave this here as I currently don't have enough time to fix it myself (but might in the future).

I'm using Tab Center Redux on the right side of my screen with compact tabs. I have one or more pinned tabs. If I close a tab and it focuses (and thus, scrolls) the previously used tab, the tab will be hidden behind the pinned tabs if it is close to the top. Maybe it's easier with a step by step reproducer:

~1. Open a bunch of tabs, enough to have the list scrolling
2. Pin one or more tabs
3. Activate a tab close to the top (works best with 1st non-pinned tab)
4. Scroll down and activate last tab
5. Close last tab
6. Observe Tabcenter scroll up to activate and show the previously active tab. However, it stops just shy of the target so it's hidden behind the pinned tab bar and you have to manually scroll to see it.~

EDIT: the previous steps didn't show the issue. This here does:

1. Open a bunch of tabs, enough to have the list scrolling
2. Pin one or more tabs
3. Activate a pinned tab
4. Open a tab in the background (i.e. ⌘ + click on Mac)
5. It will open the tab behind the pinned tab bar, and you need to scroll up to see the newly opened tab.

I can provide a small screen-capture in case it's needed.

I'm using Tabcenter 0.7.1 on FF Developer Edition 70.0b13 (64-bit), MacOS 10.15, but I've seen this issue with standard FF and earlier OS versions.

**Comment by ariasuni** [comment]
If I remember correctly, it’s a bug I fixed a while ago in [Tab Center Reborn](https://addons.mozilla.org/firefox/addon/tabcenter-reborn/) (it’s the continuation of Tab Center Redux).

**Comment by d53dave** [comment]
Indeed, I tried Tab Center Reborn and it works as expected.
