### ISSUE TITLE
Add support for drag-and-drop links and tabs from other windows onto sidebar

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#45]
Possibly with a tab drop indicator for dropping in between tabs.

>SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data[Learn More]  index.js:327:35
	onDrop moz-extension://689dadd1-17e6-4b35-be65-c45d9a899929/index.js:327:35
	setupListeners/< moz-extension://689dadd1-17e6-4b35-be65-c45d9a899929/index.js:135:44

**Comment by eoger** [comment]
It should be working with Tab Center tabs. Doesn't work with "real" tabs.

**Comment by Keith94** [comment]
I use TC Redux in Nightly 56, but dropping links does not work for me. See recording:

![2017-06-16_17-00-58](https://user-images.githubusercontent.com/5490615/27248237-9dd2d8d4-52b5-11e7-8152-7dfbaf7810e3.gif)

**Comment by eoger** [comment]
Right, other things than tabs are not supported yet.
