### ISSUE TITLE
Container tab menu should close when clicking on website content

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#49]

**Comment by eoger** [comment]
Please provide more context.
https://github.com/eoger/tabcenter-redux/commit/4060e3b38776f47a7a79c5293a5a00b2f25ad5a4 should have fixed it.

**Comment by Keith94** [comment]
4060e3b fixes the _tab context menu_, however the _container tabs_ menu needs the same fix (long click on new tab button).

**Comment by eoger** [comment]
Right, good point

**Comment by Keith94** [comment]
Yes, sorry I didn't make that clear before.
