### ISSUE TITLE
Implement reverse tab order

### ISSUE THREAD

**Issue by eoger** [eoger/tabcenter-redux#5]

**Comment by bwinton** [comment]
My strong suggestion is to not do this.  It was an interesting experiment, but led to literally no end of problems, and totally wasn't worth it. 😉

**Comment by Keith94** [comment]
Perhaps there could be a better way to implement this feature that wouldn't lead to so many bugs as last time.

**Comment by bwinton** [comment]
It wasn't just bugs, as much as that everyone who wanted it wanted it to act slightly differently, so no-one was happy with the one checkbox.  (For instance, should ctrl-tab take you up or down? When opening a new tab, should it go at the top or the bottom? Should pinned tabs stick to the top or the bottom? Those are just a few examples off the top of my head where different people wanted different things, and it leads to a combinatorial explosion of possibilities for little real usability gains.)

**Comment by kumar303** [comment]
Rather than *reverse* the tab order, an option to open new tabs at the top would be immensely helpful. When I have a long list of tabs, I'd rather get thrown to the top of my list because that's where all my pinned tabs are. I also like this because it stacks my tab history more chronologically with my newest visited tabs at the top.

**Comment by bwinton** [comment]
That sounds like a different WebExtension, and I _think_ @autonome might have already wrote it…  :)

**Comment by kumar303** [comment]
Interesting. Do you have a link?

**Comment by bwinton** [comment]
https://github.com/autonome/Always-Right maybe?  (He was talking about it in IRC yesterday or the day before, but didn't mention which one.)

**Comment by kumar303** [comment]
That's exactly what I wanted! Thank you. And thanks @autonome ❤️

**Comment by autonome** [comment]
Life begins today, @kumar303.

**Comment by eoger** [comment]
This will probably never happen, closing this bug!
