### ISSUE TITLE
0.3.1 not effective on Firefox 53.0.2 on FreeBSD

### ISSUE THREAD

**Issue by grahamperrin** [eoger/tabcenter-redux#50]
I installed 0.3.1 for Linux to Firefox 53.0.2 (64-bit) on TrueOS Desktop, which is based on FreeBSD-CURRENT. A sidebar did not appear so … 

… at an adjacent computer with pre-release build 17A264c of Mac OS X 10.13, I installed the extension to Firefox 54. Again, no sidebar; unless I'm missing something, the installed extension is not effective.

**Comment by Screwtapello** [comment]
There should be a Sidebar button you can add to the FIrefox navigation bar that lets you choose to show the Bookmarks sidebar, History sidebar, Synced Tabs sidebar, or any other sidebar installed by an addon (in this case, the "Tabs" sidebar).

If your Firefox is configured to show the menu-bar, you may also be able to control the sidebar from the View menu.

**Comment by Keith94** [comment]
You may also want to check Firefox 55 or later, I ran into issues with the add-on on versions before 55.

**Comment by grahamperrin** [comment]
Thank you both. 

After not finding what's required in the Sidebars submenu of Firefox 53.0.2, I did not think to try the Sidebars submenu in 54.0. 

Now with 0.3.1 on 54.0 on Mac OS X I do have the _Tabs_ sidebar. 

TrueOS Desktop has not yet gained [the port of 54](http://www.freshports.org/www/firefox). I'll test with 54 on a different FreeBSD-based system.

**Comment by grahamperrin** [comment]
Success with 0.3.1 for Linux on Firefox **54.0** on GhostBSD, 

```text
$ freebsd-version
10.3-RELEASE-p19
```

![2017-06-18 07-55-11](https://user-images.githubusercontent.com/192271/27258789-d1acd3d4-53fb-11e7-8c62-399e5f4f9ed7.png)

**Comment by eoger** [comment]
Nice, thank you for the investigation, I have bumped up the minimum version of the add-on to 54.
