### ISSUE TITLE
sometimes, some tabs are missing from the sidebar

### ISSUE THREAD

**Issue by grahamperrin** [eoger/tabcenter-redux#51]
Oberved: 

- first with 0.3.1 for Linux on Firefox 54.0 on FreeBSD
- then with 0.3.1 on Firefox 54.0 on pre-release build 17A264c of Mac OS X 10.13. 

![2017-06-18 08-15-35](https://user-images.githubusercontent.com/192271/27258902-5a8a75c4-53fe-11e7-8a89-e1bfb5f89fc1.png)

@Keith94 

> … ran into issues with the add-on on versions before 55.

Is this one of those issues?

**Comment by Keith94** [comment]
>Is this one of those issues?

Yes, it doesn't seem to support versions <55. Tab list is completely broken for me.

**Comment by eoger** [comment]
I was actually going to open a bug to say that the add-on looks terrible on Firefox 54.
I bumped up the minimum version to 55 and added a disclaimer message to the listing description.
