### ISSUE TITLE
Middle clicking tabs triggers autoscrolling when scroll bar is present

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#53]
When you middle click the tab gets closed but at the same time the autoscrolling action is triggered (only when tabs are overflowing).

**Comment by Smile4ever** [comment]
I did this (kind of) for my addon Middle Click On Page Closes Tab. I filed a bug at Mozilla to make this easier: https://bugzilla.mozilla.org/show_bug.cgi?id=1374188

**Comment by Livven** [comment]
@Smile4ever No action from Mozilla is needed since preventing middle click autoscrolling is possible with standard Javascript (see #60). It's just a bit tricky since you either have to use `e.preventDefault()` or directly set the event (i.e. `element.onmouse = handler`), whereas using `addEventListener` together with `return false` won't work.

**Comment by Smile4ever** [comment]
@Livven I did try e.preventDefault() in my local copy and it didn't fix the issue for me. Anyway, I'm going to try it and report back if it's not working. 🙂

**Comment by Livven** [comment]
@Smile4ever FWIW I'm on 55.0b2. If that doesn't work try `element.onmousedown = handler` (with either `return false` or `e.preventDefault()`).

**Comment by Smile4ever** [comment]
The fix does not work for me. Tested on Windows using Firefox 55b2 and Nightly 56.0a1 2017-06-19. I will try this on Linux as well.

**Comment by Smile4ever** [comment]
> @Smile4ever No action from Mozilla is needed since preventing middle click autoscrolling is possible with standard Javascript (see #60). It's just a bit tricky since you either have to use e.preventDefault() or directly set the event handler (i.e. element.onmousedown = handler), whereas using addEventListener together with return false won't work.

That's why I asked for an WebExtensions API to disable autoscrolling, since Firefox has a setting built in that controls autoscrolling. Being able to set that would make it so much easier.

**Comment by Livven** [comment]
@Smile4ever Can you [try autoscrolling in each of the four boxes here](https://jsfiddle.net/Lgf1dLw4/) and let me know where it works and where it does not? FYI it should only work in the third one and does so for me across Firefox, Chrome and Edge.

**Comment by Smile4ever** [comment]
@Livven It only works in the third, but in Tab Center Redux it is still an issue for me. It is always reproducible on my system. I've tried a different computer mouse (you never know) but the issue persists.

**Comment by Smile4ever** [comment]
@Livven I've tested this on Linux as well, there is no problem on Linux. I think this is Windows specific.

**Comment by Smile4ever** [comment]
@Livven I tested this again on Windows, and now the issue is gone.. Weird. Thanks for your fix!
