### ISSUE TITLE
Localisation: extension name

### ISSUE THREAD

**Issue by Smile4ever** [eoger/tabcenter-redux#57]
I noticed "Tab Center Redux" is present in messages.json in at least the English, French and Dutch locale. Shouldn't this be "TabCenter Redux"?

**Comment by eoger** [comment]
You are right, it should probably be consistent everywhere.  
There is a lot of copy-pasted long texts I haven't got time to review.
I think should be Tab Center Redux, with the space.

**Comment by eoger** [comment]
Fixed by https://github.com/eoger/tabcenter-redux/pull/68. Please reopen if needed.
