### ISSUE TITLE
Add right-click context menu for search bar

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#62]
Add menu with the following options. Also menu should close when focus is lost.

```
Undo
——————————
Cut
Copy
Paste
Delete
——————————
Select All
```

**Comment by eoger** [comment]
No need to re-implement it, it is disabled because of [this](https://github.com/eoger/tabcenter-redux/blob/master/src/tabcenter.js#L145).
We could modify this code to allow the context menu inside the searchbox input
