### ISSUE TITLE
Minor: Labels should use the same letter case

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#65]
Always Shrink Tabs => Always shrink tabs
or
Dark theme => Dark Theme

![image](https://user-images.githubusercontent.com/5490615/27315311-c1993c16-552d-11e7-8b33-47de40aab8c8.png)

**Comment by eoger** [comment]
Always Shrink Tabs should probably be renamed Compact Mode imo, that was poor naming on my part.
