### ISSUE TITLE
Add 'Undo Close Tab' and 'Bookmark All Tabs...' to menu

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#66]

**Comment by eoger** [comment]
I'm not sure there is a WebExtension API to query the closed tabs history, which means we would have to keep a list of recently closed tabs, not super keen to do that to be honest.

**Comment by yfdyh000** [comment]
@eoger https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/sessions/getRecentlyClosed

**Comment by mark1m4** [comment]
+1 for Undo Close Tab. But it would actually be better to show the original Firefox menu.
