### ISSUE TITLE
Allow to open a new tab in a different container

### ISSUE THREAD

**Issue by eoger** [eoger/tabcenter-redux#7]
In the original TabCenter this is done by long-pressing New Tab, sadly there is no good way to show a native menu yet.

**Comment by jonathanKingston** [comment]
There is if users have containers enabled you can implement the same menu by querying the `browser.contextualIdentities.query({})` method.
This will gain the same list of icon, name and colour which can be used to replicate something similar.

**Comment by eoger** [comment]
Yes, I think I will have to implement the menu myself in HTML.
