### ISSUE TITLE
Tab context menu should use the same font size as the rest of Tab Center Redux

### ISSUE THREAD

**Issue by Smile4ever** [eoger/tabcenter-redux#71]
The tab context menu should use the same font size as the rest of Tab Center Redux. Its font size is way too large now.

**Comment by eoger** [comment]
I agree it's a bit too large, the styling of this context menu is pretty basic.

**Comment by Screwtapello** [comment]
For me on Linux, the context menu looks exactly right, but the tab labels are weirdly small; definitely smaller than the old Tab Center ones.

**Comment by Smile4ever** [comment]
> For me on Linux, the context menu looks exactly right, but the tab labels are weirdly small; definitely smaller than the old Tab Center ones.

Tab context menu on Linux looks good, but not on Windows. And Screwtapello is right, the labels on the tabs are smaller than they used to be with Tab Center.

**Comment by eoger** [comment]
This was fixed by https://github.com/eoger/tabcenter-redux/commit/2969265648861c27c94f996f868f2bec5f08928c, closing!
