### ISSUE TITLE
Tabs are missing top border

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#86]
Tabs appear to have no top border which looks a bit inconsistent when selected/hovered/dragged.

![image](https://user-images.githubusercontent.com/5490615/27415242-d8b097bc-56ba-11e7-9f99-54469739ab5f.png)

**Comment by yfdyh000** [comment]
The line is `class="tab-context"`. If a blue line is at the top, It might be like a load progress bar.

**Comment by asamuzaK** [comment]
I haven't looked into CSS of tabcenter-redux, but here is a sample for collapsed border.
[collapsed border test](http://asamuzak.jp/test/border_collapse_test "collapsed border test")
Will it help?

**Comment by Keith94** [comment]
Fixed in [Tab Center Reborn](https://addons.mozilla.org/en-CA/firefox/addon/tabcenter-reborn/)
