### ISSUE TITLE
Remove the auto-shrink/move to top buttons in the top menu

### ISSUE THREAD

**Issue by eoger** [eoger/tabcenter-redux#9]
They are currently impossible to implement, maybe replace them by a Settings button?

**Comment by lissyx** [comment]
I would be sad to see that feature leaving, this was one of the most important one for me in the Tab Center test pilot: space waste without that is too important. As per our discussion on IRC, it seems the WebExtensions APIs are not (yet?) ready to take care of that and you suggested a workaround of "Compact mode".

**Comment by eoger** [comment]
Closed by https://github.com/eoger/tabcenter-redux/commit/9fd83d000a615d6fc174b7aa0f0ece5b48b9f5d6.
