### ISSUE TITLE
Show the New Tab container menu on hover

### ISSUE THREAD

**Issue by Smile4ever** [eoger/tabcenter-redux#90]
Long click + click is not very optimal, hover + click would be better to show the New Tab container menu. It will also make this feature more discoverable.

**Comment by yfdyh000** [comment]
I added right-click action in #80.

**Comment by Tronix117** [comment]
I think it should be great to give the option in the settings to choose if we want this menu to appear on a left-click or on a right-click.

A majority of people uses CTRL/CMD + T anyway, in my case the only use of this "+" button is to access to the container menu.
