### ISSUE TITLE
Disallow scrolling when context menus are open

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#94]
* Scrolling tabs with mouse wheel should be disabled when menus are open
* Clicking on scroll bar should close the context menus if they're open

**Comment by eoger** [comment]
At this point I'm starting to think that the HTML context menu is _good enough_ and we shouldn't add more complexity in the code.
I do really hope fully-customizable native context menus will be a thing in the future iterations of Firefox.

**Comment by Keith94** [comment]
Agreed.

**Comment by eoger** [comment]
Closing since no one else complained :) Thanks for QA though!
