### ISSUE TITLE
Use system themes, colors, and icons

### ISSUE THREAD

**Issue by mlissner** [eoger/tabcenter-redux#96]
The old tab center used the system dark theme, which meant that it nicely matched the rest of the browser. I appreciate that some effort was made to add a dark theme to redux, but it doesn't match the rest of the browser (and OS), and looks weird. For example, it's blue while the rest of my browser is dark gray.

Also, my operating system (Ubuntu) has an option for setting all programs to use the dark theme, so having an option in the UI is weird, especially since it's not clicked by default on my system. The rest of the browser is dark by default...why not the sidebar? The last thing I'd think to do is go hunting for an option.

**Comment by mlissner** [comment]
Just noticed: This also applies to the right click menu.

**Comment by mlissner** [comment]
I just updated the title because I realized this is a bigger thing:

 - We aren't using the system colors for dark themes (and I suspect not for light themes either)
 - We aren't using the default icons (which is a shame, b/c I understand they're being redone)
 - We aren't using the system font sizes
 - Context menus don't look right
 - Etc?

I have no idea how feasible this is, but coming from using Tab Center, which did all of the above (I think), it's quite jarring not to have the native Chrome.

**Comment by eoger** [comment]
Related: https://github.com/eoger/tabcenter-redux/issues/6 https://github.com/eoger/tabcenter-redux/issues/99

**Comment by eoger** [comment]
I believe we are doing an OK job now, and we have OS specific CSS code too.
