### ISSUE TITLE
Pages without favicon get a broken icon intermittently

### ISSUE THREAD

**Issue by martinthomson** [eoger/tabcenter-redux#97]
Not sure about the cause of this, but I get a lot of these:

![](http://i.imgur.com/hsFJGst.png)

**Comment by eoger** [comment]
Yes, we should definitely handle our favicons better. https://github.com/eoger/tabcenter-redux/pull/100/files was a good start but the author closed it, maybe someone wants to take it over?

**Comment by Kenny11CZ** [comment]
Works fine for me... Is it solved or I'm just unable to replicate?
![favicon](https://user-images.githubusercontent.com/8071168/35462604-eec71d30-02ec-11e8-8a00-6bb22bfc0610.png)

**Comment by martinthomson** [comment]
Yes, I can confirm that this hasn't appeared in a while.  Not sure if that is as a direct result of a targeted fix, or secondary consequence of some other change.  I'll reopen if this reappears.
