### ISSUE TITLE
Tab title text too small

### ISSUE THREAD

**Issue by DmitriK** [eoger/tabcenter-redux#99]
I have a monitor with slightly higher DPI (not crazy retina levels, 109dpi vs 96 standard, so sizes aren't doubled or anything like that), so I tend to run my system fonts 2 sizes up or so. Tabcenter redux hard codes an 11px font, which is uncomfortably small for me, and doesn't match the rest of the UI. Request that no size is specified in the CSS so that it gets inherited from the default browser UI.

**Comment by Screwtapello** [comment]
Can't we just say `font: caption` to automatically get the correct typeface and size from the current OS theme?

**Comment by eoger** [comment]
Font-size is kinda tricky... We bumped the font-size to 12px and in my opinion this is too big 😄
It looks like `font: message-box;` is used by the native tabs implementation. We should probably use this instead of hard-coding.

**Comment by eoger** [comment]
Fixed by https://github.com/eoger/tabcenter-redux/commit/2969265648861c27c94f996f868f2bec5f08928c, please reopen if I missed something.
